
#line 3 "lex.cgrpyy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer cgrpyy_create_buffer
#define yy_delete_buffer cgrpyy_delete_buffer
#define yy_flex_debug cgrpyy_flex_debug
#define yy_init_buffer cgrpyy_init_buffer
#define yy_flush_buffer cgrpyy_flush_buffer
#define yy_load_buffer_state cgrpyy_load_buffer_state
#define yy_switch_to_buffer cgrpyy_switch_to_buffer
#define yyin cgrpyyin
#define yyleng cgrpyyleng
#define yylex cgrpyylex
#define yylineno cgrpyylineno
#define yyout cgrpyyout
#define yyrestart cgrpyyrestart
#define yytext cgrpyytext
#define yywrap cgrpyywrap
#define yyalloc cgrpyyalloc
#define yyrealloc cgrpyyrealloc
#define yyfree cgrpyyfree

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE cgrpyyrestart(cgrpyyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int cgrpyyleng;

extern FILE *cgrpyyin, *cgrpyyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cgrpyytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up cgrpyytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via cgrpyyrestart()), so that the user can continue scanning by
	 * just pointing cgrpyyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when cgrpyytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int cgrpyyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow cgrpyywrap()'s to do buffer switches
 * instead of setting up a fresh cgrpyyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void cgrpyyrestart (FILE *input_file  );
void cgrpyy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE cgrpyy_create_buffer (FILE *file,int size  );
void cgrpyy_delete_buffer (YY_BUFFER_STATE b  );
void cgrpyy_flush_buffer (YY_BUFFER_STATE b  );
void cgrpyypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void cgrpyypop_buffer_state (void );

static void cgrpyyensure_buffer_stack (void );
static void cgrpyy_load_buffer_state (void );
static void cgrpyy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER cgrpyy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE cgrpyy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE cgrpyy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE cgrpyy_scan_bytes (yyconst char *bytes,int len  );

void *cgrpyyalloc (yy_size_t  );
void *cgrpyyrealloc (void *,yy_size_t  );
void cgrpyyfree (void *  );

#define yy_new_buffer cgrpyy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        cgrpyyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cgrpyy_create_buffer(cgrpyyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        cgrpyyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            cgrpyy_create_buffer(cgrpyyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

typedef unsigned char YY_CHAR;

FILE *cgrpyyin = (FILE *) 0, *cgrpyyout = (FILE *) 0;

typedef int yy_state_type;

extern int cgrpyylineno;

int cgrpyylineno = 1;

extern char *cgrpyytext;
#define yytext_ptr cgrpyytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up cgrpyytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	cgrpyyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[407] =
    {   0,
        0,    0,   70,   69,    2,    6,    5,   56,   69,   69,
       69,   69,   61,   69,   59,   69,   66,   60,   58,   50,
       69,   51,   62,   45,   68,   46,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   52,   69,   53,    2,   69,    2,    0,   49,
        0,   64,    0,    4,   54,    0,   67,   63,    0,   66,
       48,   57,    0,   62,    0,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   67,   55,    2,    0,    0,    3,    0,   63,    0,

       65,    0,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,    0,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,    0,    0,   62,   62,   47,   62,
       62,   62,   62,    0,   62,   62,   62,   62,   62,   62,
       62,   62,   22,   62,    0,   62,   62,   13,   62,   62,
       62,   62,   62,   62,   14,   62,   62,   23,   18,    0,
        0,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       15,   62,   62,   62,   25,   62,   33,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,    0,    0,    0,

        0,   62,   20,   62,   62,   62,   62,   62,   62,   24,
       62,   62,   62,   62,   19,   62,   62,   62,   62,   62,
       16,   62,   62,   62,    0,    0,   62,    0,    0,   62,
       62,   62,   62,   62,    0,    0,    0,    0,    0,   62,
       62,   62,   62,   62,   62,   62,   62,    0,    7,   62,
       62,   62,   62,   28,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   30,   62,   62,   62,
       17,   62,    0,   62,   62,   62,    0,    0,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,    8,    0,
        0,   62,    0,   62,    0,   62,   62,   62,   62,   62,

       62,   10,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,    0,   42,   62,   62,   62,
       62,   21,    9,   36,   62,   62,   62,   62,   62,   62,
       62,   62,    0,   62,   62,    0,    0,   62,   62,   62,
        0,   62,   62,   62,   62,   11,   62,   62,   62,   62,
       62,   62,   62,    1,   62,   62,   62,   62,    0,   62,
       40,   39,   31,   62,   62,   62,   62,   62,   41,   62,
       38,   62,   62,   62,   62,   62,   12,   62,   62,   32,
       43,   62,   62,   62,   62,   62,   62,   62,   37,   62,
       62,   62,   62,   26,   27,   29,   62,    0,   44,   34,

       62,   62,   62,   62,   35,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    5,    6,    7,    1,    1,    8,    9,    1,
        1,   10,   11,   12,   13,   14,   15,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   17,   18,   19,
       20,   21,    1,    1,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       22,   22,   22,   22,   22,   22,   22,   22,   22,   22,
       23,   24,   25,    1,   22,    1,   26,   27,   28,   29,

       30,   31,   32,   33,   34,   22,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
       49,   22,   50,   51,   52,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[53] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    4,    3,    1,    1,    1,    1,
        1,    5,    1,    1,    1,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    1,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[415] =
    {   0,
        0,   51,  776,  777,   52,  777,  777,  755,  768,  770,
      764,  762,  777,  754,  777,    0,   41,  777,  777,  777,
       40,  777,  756,  736,  777,  777,   43,   49,   50,   51,
       52,   53,   55,   54,   58,   65,   56,   67,   62,   83,
       57,   60,  777,   61,  777,   95,   71,  106,  764,  777,
      760,  777,  762,  777,  777,  755,  100,  748,  746,  101,
      777,  777,  748,  747,  723,   97,   85,   86,  106,  107,
      108,  109,  110,  111,  112,  114,  118,  116,  115,  122,
      123,  745,  120,  124,  135,  145,  125,  129,  154,  130,
      159,  741,  777,  138,  753,  752,  777,  136,  739,    0,

      737,  713,  137,  164,  162,  166,  168,  169,  171,  738,
      172,  174,  173,  178,  180,  183,  181,  182,  184,  185,
      737,  189,  190,  186,  188,  192,  198,  191,  202,  207,
      209,  213,  217,  193,  228,  722,  219,  223,  225,  227,
      230,  231,  232,  233,  235,  236,  239,  238,  237,  247,
      241,  246,  735,  242,  248,  251,  249,  734,  255,  250,
      252,  260,  277,  258,  733,  278,  732,  731,  730,  263,
      716,  728,  257,  280,  281,  282,  285,  289,  290,  288,
      727,  295,  293,  291,  726,  296,  725,  297,  298,  299,
      302,  300,  304,  305,  306,  301,  307,  313,  324,  701,

      317,  723,  722,  320,  324,  327,  328,  333,  721,  720,
      719,  718,  717,  716,  715,  334,  336,  337,  347,  344,
      714,  345,  349,  348,  360,  701,  351,  352,  358,  354,
      353,  357,  359,  361,  363,  362,  366,  378,  379,  367,
      385,  364,  394,  365,  395,  396,  397,  408,  777,  399,
      404,  405,  712,  711,  406,  407,  408,  410,  409,  415,
      416,  418,  419,  420,  421,  710,  709,  708,  430,  707,
      706,  426,  443,  434,  435,  436,  439,  441,  443,  445,
      447,  449,  450,  452,  453,  454,  459,  462,  705,  460,
      457,  463,  467,  466,  481,  472,  469,  474,  479,  478,

      490,  704,  488,  489,  491,  493,  494,  495,  497,  500,
      498,  501,  703,  503,  504,  521,  702,  519,  508,  509,
      701,  700,  685,  680,  512,  510,  525,  528,  521,  529,
      530,  532,  534,  538,  541,  552,  680,  544,  545,  553,
      550,  666,  554,  555,  559,  665,  560,  561,  562,  564,
      566,  565,  569,  777,  573,  576,  568,  572,  575,  579,
      663,  662,  661,  577,  578,  580,  581,  590,  660,  597,
      658,  589,  584,  602,  604,  605,  657,  608,  610,  652,
      648,  612,  616,  617,  618,  620,  621,  622,  647,  624,
      623,  645,  628,  644,  640,  631,  629,  637,  639,  138,

      633,  641,  636,  638,  134,  777,  681,  686,  691,   71,
      694,  699,  702,  707
    } ;

static yyconst flex_int16_t yy_def[415] =
    {   0,
      406,    1,  406,  406,  406,  406,  406,  406,  407,  408,
      406,  409,  406,  406,  406,  410,  406,  406,  406,  406,
      406,  406,  411,  406,  406,  406,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  406,  406,  406,  406,  412,  406,  408,  406,
      407,  406,  408,  406,  406,  409,  406,  413,  406,  406,
      406,  406,  411,  411,  406,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  406,  406,  406,  412,  412,  406,  412,  413,  410,

      406,  406,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  412,  406,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  412,
      406,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  412,  406,

      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  412,  406,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  412,  406,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  412,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  412,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  414,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  414,  412,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  406,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,
      411,  411,  411,  411,  411,  411,  411,  411,  411,  411,

      411,  411,  411,  411,  411,    0,  406,  406,  406,  406,
      406,  406,  406,  406
    } ;

static yyconst flex_int16_t yy_nxt[830] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   14,    4,   16,   17,   18,   19,   20,   21,
       22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
       23,   32,   23,   33,   23,   34,   35,   36,   37,   38,
       23,   39,   40,   41,   42,   23,   23,   23,   23,   43,
       44,   45,   46,   48,   59,   63,   60,   47,   49,   61,
       62,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   66,   63,   97,   63,   58,   92,   63,   67,   63,
       74,   70,   69,   79,   68,   71,   77,   80,   72,   73,
       81,   86,   84,   78,   76,   63,   94,   63,   63,   75,

       83,   95,   91,   82,   98,   90,   87,   48,   85,   63,
       88,   93,   49,   59,   59,   57,   60,  105,   63,   63,
       63,   63,   63,   63,   63,  103,   63,   63,   63,   89,
       63,  104,   63,  108,   63,   63,   63,   63,   97,   94,
      117,   63,   63,  106,   95,  109,   63,   63,  107,   63,
       63,  112,  113,  111,  110,  114,  115,   63,  118,  119,
      130,  131,  116,  121,  124,  122,   63,  123,  125,  133,
      126,   63,  127,  135,   63,  137,   63,  139,   63,  132,
       63,   63,  128,   63,   63,   63,   63,  129,  134,  138,
       63,  140,   63,   63,   63,   63,   63,   63,   63,  145,

       63,   63,   63,   63,   63,   63,  141,  143,  150,  151,
       63,  142,  146,  153,   63,  149,  148,  147,  156,   63,
      152,   63,  158,  154,  163,   63,  160,  161,  159,   63,
       97,   63,  157,  162,  169,   63,  165,   63,  166,   63,
      139,  164,   63,   63,   63,   63,  168,   63,   63,   63,
       63,   63,  167,   63,   63,  170,  172,  177,   63,   63,
       63,   63,   63,   63,   63,   97,  183,   63,  174,   63,
       63,  173,   63,  176,  175,  178,  179,  180,  181,  182,
      184,  187,  190,  185,  191,  194,  188,  186,  189,   63,
       63,  192,   63,   63,   63,  193,  196,   63,  199,  202,

       63,   63,   63,   63,  195,   63,  197,   63,   63,   63,
       63,   63,   63,   63,   63,  205,   63,   63,   63,   63,
      204,  207,  206,  208,  210,   63,   97,  214,  203,   63,
      211,  209,  229,  218,  212,  221,   63,  219,  222,   63,
       63,  215,  216,  217,  213,   63,   63,  220,   63,   63,
      230,  223,  224,  233,  231,  232,   63,   63,  227,   63,
       63,   63,   97,   63,   63,   63,   63,  240,  225,   63,
       63,   63,  234,   63,   63,   63,   63,   63,   63,   63,
      242,  241,  251,  243,  246,  252,  244,  245,  248,  247,
       63,   63,  255,  258,  259,  250,  253,   63,  269,  261,

      256,  254,  260,  262,  257,  265,   63,   63,   63,   63,
       97,   63,  267,  263,  266,  264,   63,   63,   63,   63,
       63,   63,   63,  268,  270,  271,  272,   63,   63,  275,
       63,   63,   63,   63,  274,  282,  280,  273,   63,  279,
      284,  281,   63,  276,  295,   97,   63,   63,   63,  288,
      283,   63,  287,   63,  285,   63,  286,   63,  289,   63,
      292,   63,   63,  296,   63,   63,   63,  300,  294,   63,
      297,   63,   63,  298,   63,   63,  304,  299,   63,   63,
      301,   63,  295,   97,   63,  303,   63,  302,  305,  316,
       63,   63,  312,  306,  314,  309,  307,  308,  310,  311,

       63,   63,   63,   63,  318,   63,   63,   63,  315,   63,
       63,  313,   63,   63,  317,   63,   63,  319,  320,  322,
       63,   63,   63,   97,   63,  323,  321,  327,  328,  337,
      329,   63,  324,   63,  332,  325,  326,   63,  330,  331,
       63,   63,   63,  343,   63,  338,   63,  334,  335,  339,
       63,  342,  340,   63,   97,  344,   63,   63,  345,  350,
      337,  351,   63,  348,  346,   63,   63,   63,  349,  355,
      347,   63,   63,   63,   63,  358,   63,   63,   63,  352,
       63,   63,  353,  356,   63,   63,  357,   63,   63,   63,
       63,   63,   63,   63,  366,  365,   63,  360,  369,  364,

      370,   63,   63,  361,  367,  374,  372,  362,  363,   63,
      368,  371,  375,  373,   63,  383,   63,   63,  376,  380,
       63,  377,   63,  378,   63,  379,  382,  384,   63,   63,
       63,  381,   63,   63,   63,   63,   63,  387,  386,  396,
       63,   63,  385,   63,  391,   63,  396,  388,   63,   63,
       63,   63,   63,   63,  389,  392,   63,  398,  402,   63,
       63,  390,  394,  393,   63,  395,  397,  401,  403,   63,
       63,  400,   63,   63,   63,   63,  399,   63,  359,  404,
      405,   51,  354,   51,   51,   51,   53,   53,   53,   53,
       53,   56,   63,   56,   56,   56,   64,   63,   64,   96,

       96,   96,   96,   96,   99,   99,   99,  336,  336,  336,
      336,  336,   63,  341,   63,  333,   63,   63,   63,  293,
      291,   63,  290,  278,  277,  249,   63,   63,  239,  238,
      237,  236,   63,  235,   63,  228,  226,   63,   63,   63,
      201,  200,   63,   63,  198,   63,   63,   63,  171,  155,
      144,  136,  101,  100,   97,   97,   92,  120,  102,   63,
       63,  101,  100,   52,   54,   52,   54,   65,   63,   57,
       52,   55,   54,   52,   50,  406,    3,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406
    } ;

static yyconst flex_int16_t yy_chk[830] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    2,    5,   17,   27,   17,    2,    5,   21,
       21,   28,   29,   30,   31,   32,   34,   33,   37,   41,
       35,   27,   42,   47,   39,  410,   44,   36,   27,   38,
       30,   29,   28,   34,   27,   29,   33,   35,   29,   29,
       36,   39,   38,   33,   32,   40,   46,   67,   68,   31,

       37,   46,   42,   36,   47,   41,   39,   48,   38,   66,
       40,   44,   48,   57,   60,   57,   60,   68,   69,   70,
       71,   72,   73,   74,   75,   66,   76,   79,   78,   40,
       77,   67,   83,   71,   80,   81,   84,   87,   98,   94,
       79,   88,   90,   69,   94,   72,  405,   85,   70,  103,
      400,   75,   76,   74,   73,   77,   78,   86,   80,   81,
       87,   88,   78,   83,   85,   84,   89,   84,   85,   90,
       86,   91,   86,   98,  105,  103,  104,  105,  106,   89,
      107,  108,   86,  109,  111,  113,  112,   86,   91,  104,
      114,  106,  115,  117,  118,  116,  119,  120,  124,  111,

      125,  122,  123,  128,  126,  134,  107,  109,  116,  117,
      127,  108,  112,  119,  129,  115,  114,  113,  122,  130,
      118,  131,  123,  120,  128,  132,  125,  126,  124,  133,
      135,  137,  122,  127,  134,  138,  130,  139,  131,  140,
      139,  129,  141,  142,  143,  144,  133,  145,  146,  149,
      148,  147,  132,  151,  154,  135,  137,  143,  152,  150,
      155,  157,  160,  156,  161,  170,  149,  159,  140,  173,
      164,  138,  162,  142,  141,  144,  145,  146,  147,  148,
      150,  154,  157,  151,  159,  162,  155,  152,  156,  163,
      166,  160,  174,  175,  176,  161,  164,  177,  170,  173,

      180,  178,  179,  184,  163,  183,  166,  182,  186,  188,
      189,  190,  192,  196,  191,  176,  193,  194,  195,  197,
      175,  178,  177,  179,  182,  198,  199,  188,  174,  201,
      183,  180,  204,  192,  184,  195,  205,  193,  196,  206,
      207,  189,  190,  191,  186,  208,  216,  194,  217,  218,
      204,  197,  198,  207,  205,  206,  220,  222,  201,  219,
      224,  223,  225,  227,  228,  231,  230,  216,  199,  232,
      229,  233,  208,  234,  236,  235,  242,  244,  237,  240,
      218,  217,  228,  219,  223,  229,  220,  222,  225,  224,
      238,  239,  232,  235,  235,  227,  230,  241,  244,  236,

      233,  231,  235,  237,  234,  240,  243,  245,  246,  247,
      248,  250,  242,  238,  241,  239,  251,  252,  255,  256,
      257,  259,  258,  243,  245,  246,  247,  260,  261,  251,
      262,  263,  264,  265,  250,  258,  256,  248,  272,  255,
      260,  257,  269,  252,  273,  273,  274,  275,  276,  264,
      259,  277,  263,  278,  261,  279,  262,  280,  265,  281,
      269,  282,  283,  274,  284,  285,  286,  278,  272,  291,
      275,  287,  290,  276,  288,  292,  282,  277,  294,  293,
      279,  297,  295,  295,  296,  281,  298,  280,  283,  295,
      300,  299,  291,  284,  293,  287,  285,  286,  288,  290,

      303,  304,  301,  305,  297,  306,  307,  308,  294,  309,
      311,  292,  310,  312,  296,  314,  315,  298,  299,  301,
      319,  320,  326,  316,  325,  303,  300,  307,  308,  316,
      309,  318,  304,  329,  312,  305,  306,  327,  310,  311,
      328,  330,  331,  326,  332,  318,  333,  314,  315,  319,
      334,  325,  320,  335,  336,  327,  338,  339,  328,  333,
      336,  333,  341,  331,  329,  340,  343,  344,  332,  338,
      330,  345,  347,  348,  349,  341,  350,  352,  351,  334,
      357,  353,  335,  339,  358,  355,  340,  359,  356,  364,
      365,  360,  366,  367,  350,  349,  373,  343,  353,  348,

      355,  372,  368,  344,  351,  359,  357,  345,  347,  370,
      352,  356,  360,  358,  374,  373,  375,  376,  364,  368,
      378,  365,  379,  366,  382,  367,  372,  374,  383,  384,
      385,  370,  386,  387,  388,  391,  390,  378,  376,  390,
      393,  397,  375,  396,  384,  401,  396,  379,  403,  398,
      404,  399,  395,  402,  382,  385,  394,  392,  401,  389,
      381,  383,  387,  386,  380,  388,  391,  398,  402,  377,
      371,  397,  369,  363,  362,  361,  393,  346,  342,  403,
      404,  407,  337,  407,  407,  407,  408,  408,  408,  408,
      408,  409,  324,  409,  409,  409,  411,  323,  411,  412,

      412,  412,  412,  412,  413,  413,  413,  414,  414,  414,
      414,  414,  322,  321,  317,  313,  302,  289,  271,  270,
      268,  267,  266,  254,  253,  226,  221,  215,  214,  213,
      212,  211,  210,  209,  203,  202,  200,  187,  185,  181,
      172,  171,  169,  168,  167,  165,  158,  153,  136,  121,
      110,  102,  101,   99,   96,   95,   92,   82,   65,   64,
       63,   59,   58,   56,   53,   51,   49,   24,   23,   14,
       12,   11,   10,    9,    8,    3,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,

      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406,  406,
      406,  406,  406,  406,  406,  406,  406,  406,  406
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int cgrpyy_flex_debug;
int cgrpyy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *cgrpyytext;
#line 1 "cgrp-lexer.l"
#line 2 "cgrp-lexer.l"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <unistd.h>
#include <dirent.h>
#include <regex.h>
#include <sys/types.h>
#include <sys/stat.h>

#include "cgrp-plugin.h"
#include "cgrp-parser-types.h"
#include "cgrp-config.h"

#include "mm.h"

    
#define DEBUG(format, args...) do {            \
        if (lexer.debug)                       \
            printf("D: "format"\n" , ## args); \
    } while (0)
    

#define IGNORE(type) do {                                               \
        DEBUG("ignored %s @ %s:%d", #type, lexer_file(), lexer_line()); \
    } while (0)


/*****************************************************************************
 *                *** lexical analyser type definitions ***                  *
 *****************************************************************************/

#define RINGBUF_SIZE (16 * 1024)               /* token ring buffer size */


enum {
    INPUT_TYPE_FILE = 0,                       /* a single input file */
    INPUT_TYPE_GLOB,                           /* a shell-like pattern */
};


typedef struct lexer_input_s lexer_input_t;

#define LEXER_INPUT_COMMON                                                    \
    lexer_input_t   *prev;                     /* previous input */           \
    int              type;                     /* INPUT_TYPE_* */             \
    YY_BUFFER_STATE  yybuf;                    /* (f)lex input buffer */      \
    FILE            *fp;                       /* input stream */             \
    char            *file;                     /* input file path */          \
    int              line                      /* input line number */        \


typedef struct {                               /* a single input file */
    LEXER_INPUT_COMMON;
} lexer_file_t;


typedef struct {                               /* an input glob */
    LEXER_INPUT_COMMON;
    char    *dir;                              /* directory path */
    char    *pattern;                          /* file pattern */
    DIR     *dp;                               /* directory handle */
    regex_t  regex;                            /* globbing pattern */
} lexer_glob_t;


struct lexer_input_s {
    LEXER_INPUT_COMMON;
};


typedef struct {
    int              debug;                    /* debug lexical analysis ? */
    int              eol;                      /* last token EOL ? */
    int              eof;                      /* previous token EOF ? */
    char             tokens[RINGBUF_SIZE];     /* token ring buffer */
    int              offset;                   /* ring buffer offset */
    lexer_input_t   *input;                    /* current input */
} lexer_t;


/*
 * token types
 */

typedef enum {
    TOKEN_TYPE_UNKNOWN = 0,
    TOKEN_TYPE_IDENT,                          /* identifier */
    TOKEN_TYPE_PATH,                           /* file system path */
    TOKEN_TYPE_STRING,                         /* quoted string */
    TOKEN_TYPE_ARG,                            /* argument */
    TOKEN_TYPE_UINT,                           /* unsigned integer */
    TOKEN_TYPE_SINT,                           /* signed integer */
    TOKEN_TYPE_DOUBLE,                         /* double prec. floating */
    TOKEN_TYPE_EOL,                            /* end of line */
} token_type_t;

static lexer_t lexer = { .debug = 0 };
static int     lexer_start_token;              /* parser selector token */
static int     lexer_noinclude;                /* disable includes */

/*****************************************************************************
 *                    *** token ring buffer management ***                   *
 *****************************************************************************/

static char *
printable_token(char *token)
{
    static char buf[PATH_MAX], *p, *q;
    int         n;

    p = token;
    q = buf;
    n = sizeof(buf) - 1;
    while (*p && n > 0) {
        switch (*p) {
        case '\n':
        case '\r':
            if (n > 2) {
                *q++ = '\\';
                *q++ = *p == '\n' ? 'n': 'r';
                n -= 2;
            }
            else {
                *q++ = '.';
                n--;
            }
            break;
        default:
            *q++ = *p;
            n--;
        }
        p++;
    }
    *q = '\0';
    
    return buf;
}


static char *
token_saven(lexer_t *l, char *token, int length)
{
    int   size;
    char *saved;

    size = strlen(token);
    
    if (length > size)
        length = size;

    size = length + 1;

    if (l->offset + size >= RINGBUF_SIZE)
        l->offset = 0;
    
    saved = l->tokens + l->offset;
    l->offset += size;

    strncpy(saved, token, length);
    saved[length] = '\0';

    cgrpyylval.any.token  = saved;
    cgrpyylval.any.lineno = l->input->line;
    DEBUG("SAVED '%s'", printable_token(saved));

    return saved;
}

static char *
token_save(lexer_t *l, char *token)
{
    return token_saven(l, token, strlen(token));
}


/*****************************************************************************
 *                      *** token parsing & passing ***                      *
 *****************************************************************************/

static void
lexer_error(lexer_t *l, const char *format, ...)
{
    va_list ap;
    
    OHM_ERROR("cgrp: lexical error on line %d in file %s",
              l->input->line, l->input->file);
    
    va_start(ap, format);
    ohm_logv(OHM_LOG_ERROR, format, ap);
    va_end(ap);

    exit(1);
}


#define PASS_KEYWORD(kw) do {                                           \
        char *__token;                                                  \
                                                                        \
        DEBUG("KEYWORD %s @ %s:%d", #kw, lexer_file(), lexer_line());   \
                                                                        \
        __token = token_save(&lexer, cgrpyytext);                       \
        lexer.eol = FALSE;                                              \
                                                                        \
        if (KEYWORD_##kw == KEYWORD_CLASSIFY_ARGVX) {                   \
            __token += sizeof("classify-by-argv") - 1;                  \
            cgrpyylval.uint32.value = parse_uint32(&lexer, __token);    \
        }                                                               \
                                                                        \
        cgrpyylval.any.token = __token;                                 \
        return KEYWORD_##kw;                                            \
    } while (0)

#define PASS_TOKEN(type) do {                                           \
        char *__token;                                                  \
                                                                        \
        if (!strcmp(#type, "EOL"))                                      \
            lexer_error(&lexer, "internal error: TOKEN(EOL) !");        \
                                                                        \
        DEBUG("TOKEN %s @ %s:%d", #type, lexer_file(), lexer_line());   \
                                                                        \
        lexer.eol = FALSE;                                              \
        __token = token_save(&lexer, cgrpyytext);                       \
                                                                        \
        cgrpyylval.any.token = __token;                                 \
        return TOKEN_##type;                                            \
    } while (0)
    

#define PASS_NUMBER(type) do {                                          \
        char *__token;                                                  \
                                                                        \
        DEBUG("NUMBER %s @ %s:%d", #type, lexer_file(), lexer_line());  \
                                                                        \
        lexer.eol = FALSE;                                              \
        __token = token_save(&lexer, cgrpyytext);                       \
                                                                        \
        switch (TOKEN_TYPE_##type) {                                    \
        case TOKEN_TYPE_ARG:                                            \
            __token += sizeof("arg") - 1;                               \
            cgrpyylval.uint32.value = parse_uint32(&lexer, __token);    \
            break;                                                      \
        case TOKEN_TYPE_UINT:                                           \
            cgrpyylval.uint32.value = parse_uint32(&lexer, __token);    \
            break;                                                      \
        case TOKEN_TYPE_SINT:                                           \
            cgrpyylval.sint32.value = parse_sint32(&lexer, __token);    \
            break;                                                      \
        case TOKEN_TYPE_DOUBLE:                                         \
            cgrpyylval.dbl.value = parse_double(&lexer, __token);       \
            break;                                                      \
        default:                                                        \
            lexer_error(&lexer, "invalid numeric type %s", #type);      \
        }                                                               \
                                                                        \
        cgrpyylval.any.token = __token;                                 \
        return TOKEN_##type;                                            \
    } while (0)

#define PASS_STRING(type) do {                                          \
        char *__token, *__value;                                        \
        int   __len;                                                    \
                                                                        \
        DEBUG("TOKEN %s @ %s:%d", #type, lexer_file(), lexer_line());   \
                                                                        \
        __len   = cgrpyyleng;                                           \
        __value = cgrpyytext;                                           \
                                                                        \
        if (TOKEN_TYPE_##type == TOKEN_TYPE_STRING) {                   \
            if (__value[0] == '"' || __value[0] == '\'')                \
                __token = token_saven(&lexer, __value + 1, __len - 2);  \
            else                                                        \
                __token = token_save(&lexer, __value);                  \
        }                                                               \
        else                                                            \
            __token = token_save(&lexer, __value);                      \
                                                                        \
        cgrpyylval.string.value = __token;                              \
        lexer.eol = FALSE;                                              \
                                                                        \
        cgrpyylval.any.token = __token;                                 \
        return TOKEN_##type;                                            \
    } while (0)

#define PROCESS_EOL() do {                                              \
        char *__token;                                                  \
                                                                        \
        lexer.input->line++;                                            \
        if (lexer.eol) 							\
            IGNORE(EOL);                                                \
        else {                                                          \
            DEBUG("TOKEN EOL @ %s:%d", lexer_file(), lexer_line());     \
                                                                        \
            lexer.eol = TRUE;                                           \
            __token = token_saven(&lexer, "\n", 1);                     \
                                                                        \
            cgrpyylval.any.token = __token;                             \
            return TOKEN_EOL;                                           \
        }                                                               \
    } while (0)

#define PUSH_BACK_EOL() do {                                            \
        lexer.input->line--;                                            \
        unput('\n');                                                    \
    } while (0)


static inline u32_t
parse_uint32(lexer_t *l, char *str)
{
    u32_t  value;
    char  *end;

    value = (u32_t)strtoull(str, &end, 10);
    
    if (*end != '\0')
        lexer_error(l, "invalid unsigned integer \"%s\"", str);
    
    return value;
}


static inline s32_t
parse_sint32(lexer_t *l, char *str)
{
    s32_t  value;
    char  *end;

    value = (s32_t)strtoll(str, &end, 10);
    
    if (*end != '\0')
        lexer_error(l, "invalid signed integer \"%s\"", str);
    
    return value;
}


static inline double
parse_double(lexer_t *l, char *str)
{
    double  value;
    char   *end;

    value = strtod(str, &end);
    
    if (*end != '\0')
        lexer_error(l, "invalid double precision floating \"%s\"", str);
    
    return value;
}


/*****************************************************************************
 *                  *** lexical analyzer public interface ***                *
 *****************************************************************************/

static lexer_input_t *lexer_open_file (char *path);
static void           lexer_close_file(lexer_file_t *input);
static lexer_input_t *lexer_open_glob (char *path);
static void           lexer_close_glob(lexer_glob_t *input);
static int            lexer_more_glob(lexer_glob_t *input);


int
lexer_push_input(char *path)
{
    lexer_input_t *input;
    
    if (getenv("CGRP_LEXER_DEBUG") != NULL)
        lexer.debug = TRUE;
    
    if (strchr(path, '*') || strchr(path, '?'))
        input = lexer_open_glob(path);
    else
        input = lexer_open_file(path);

    if (input != NULL) {
        input->prev = lexer.input;
        lexer.input = input;
        
        input->yybuf = cgrpyy_create_buffer(input->fp, YY_BUF_SIZE);
        cgrpyy_switch_to_buffer(input->yybuf);
        lexer.eol = TRUE;
        return TRUE;
    }
    else {
        OHM_ERROR("cgrp: failed to open input '%s'", path);
        return FALSE;
    }
}


int
lexer_pop_input(void)
{
    lexer_input_t *input, *prev;

    if (lexer.input == NULL)
        return FALSE;

    input = lexer.input;
    prev  = input->prev;

    cgrpyy_delete_buffer(input->yybuf);

    if (input->type == INPUT_TYPE_GLOB) {
        if (lexer_more_glob((lexer_glob_t *)input)) {
            input->yybuf = cgrpyy_create_buffer(input->fp, YY_BUF_SIZE);
            cgrpyy_switch_to_buffer(input->yybuf);
            
            return TRUE;
        }
        
        lexer_close_glob((lexer_glob_t *)input);
    }
    else
        lexer_close_file((lexer_file_t *)input);

    lexer.input = prev;
    
    if (prev != NULL) {
        cgrpyy_switch_to_buffer(prev->yybuf);
        lexer.eol = TRUE;
        return TRUE;
    }
    
    return FALSE;
}


void
lexer_debug(int state)
{
    lexer.debug = state;
}


int
lexer_line(void)
{
    return lexer.input ? lexer.input->line : 0;
}


const char *
lexer_file(void)
{
    return lexer.input ? lexer.input->file : "<unknown>";
}


void
lexer_reset(int start_token)
{
    while (lexer_pop_input())
        ;

    lexer_start_token = start_token;
    lexer_noinclude   = FALSE;
}


void
lexer_disable_include(void)
{
    lexer_noinclude = TRUE;
}


void
lexer_enable_include(void)
{
    lexer_noinclude = FALSE;
}


static lexer_input_t *
lexer_open_file(char *path)
{
    lexer_file_t *input;

    if (ALLOC_OBJ(input) == NULL) {
        OHM_ERROR("cgrp: failed to allocate memory for new input %s", path);
        exit(1);
    }

    input->type = INPUT_TYPE_FILE;
    input->fp   = fopen(path, "r");

    if (input->fp == NULL) {
        OHM_ERROR("cgrp: failed to open input file '%s'", path);
        lexer_close_file(input);
        return NULL;
    }

    input->file = STRDUP(path);
    input->line = 1;

    DEBUG("opened file %s for parsing...", path);
    
    return (lexer_input_t *)input;
}


static void
lexer_close_file(lexer_file_t *input)
{
    if (input == NULL)
        return;
    
    if (input->fp)
        fclose(input->fp);
    FREE(input->file);
    
    FREE(input);
}


static lexer_input_t *
lexer_open_glob(char *path)
{
    lexer_glob_t *input;
    char         *base, *p, pattern[PATH_MAX], *q;
    int           len;

    if (ALLOC_OBJ(input) == NULL) {
        OHM_ERROR("cgrp: failed to allocate memory for input '%s'", path);
        return NULL;
    }
    
    if ((base = strrchr(path, '/')) != NULL) {
        if (((p = strchr(path, '*')) != NULL && p < base) ||
            ((p = strchr(path, '?')) != NULL && p < base)) {
            OHM_ERROR("cgrp: invalid include glob '%s'", path);
            lexer_close_glob(input);
            return NULL;
        }

        for (p = base; *p == '/'; p++)
            ;
        while (*base == '/' && base > path)
            base--;

        len        = base - path + 1;
        input->dir = ALLOC_ARR(char, len + 1);
        strncpy(input->dir, path, len);
        input->dir[len] = '\0';

        input->pattern = STRDUP(p);
    }
    else {
        input->dir     = STRDUP(".");
        input->pattern = STRDUP(path);
    }
    
    
    for (p = input->pattern, q = pattern; *p; p++) {
        switch (*p) {
        case '*': *q++ = '.';  *q++ = '*'; break;
        case '?': *q++ = '.';              break;
        case '.': *q++ = '\\'; *q++ = '.'; break;
        default:  *q++ = *p;               break;
        }
    }
    *q = '\0';

    if (regcomp(&input->regex, pattern, REG_NOSUB | REG_NEWLINE) != 0) {
        OHM_ERROR("cgrp: failed to compile regexp '%s' for '%s'",
                  pattern, input->pattern);
        lexer_close_glob(input);
        return NULL;
    }
    
    input->type = INPUT_TYPE_GLOB;
    input->dp   = opendir(input->dir);
    
    if (input->dp == NULL) {
        OHM_ERROR("cgrp: failed to open directory '%s'", input->dir);
        lexer_close_glob(input);
        return NULL;
    }

    if (lexer_more_glob(input) == FALSE) {
        lexer_close_glob(input);
        return NULL;
    }

    return (lexer_input_t *)input;
}


static void
lexer_close_glob(lexer_glob_t *input)
{
    if (input == NULL)
        return;

    FREE(input->dir);
    FREE(input->pattern);
    FREE(input->file);

    if (input->fp)
        fclose(input->fp);
    
    if (input->dp) {
        closedir(input->dp);
        input->dp = NULL;
    }

    regfree(&input->regex);
    
    FREE(input);
}
 

static int
lexer_more_glob(lexer_glob_t *input)
{
    struct dirent *de;
    struct stat    st;
    char           path[PATH_MAX];
    regmatch_t     m;

    FREE(input->file);
    input->file = NULL;
    if (input->fp != NULL) {
        fclose(input->fp);
        input->fp = NULL;
    }
    
    while ((de = readdir(input->dp)) != NULL) {
        snprintf(path, sizeof(path), "%s/%s", input->dir, de->d_name);
        DEBUG("found input candidate %s...", path);

        if (stat(path, &st) != 0 || !S_ISREG(st.st_mode))
            continue;

        if (!regexec(&input->regex, de->d_name, 1, &m, REG_NOTBOL|REG_NOTEOL)) {
            if ((input->fp = fopen(path, "r")) != NULL) {
                input->file = STRDUP(path);

                DEBUG("opened file %s for parsing...", path);
                
                return TRUE;
            }
        }
    }
    
    return FALSE;
}




/*****************************************************************************
 *                      *** miscallaneous lexer routines ***                 *
 *****************************************************************************/

static inline int
cgrpyywrap(void)
{
    return 1;
}


#line 1453 "lex.cgrpyy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int cgrpyylex_destroy (void );

int cgrpyyget_debug (void );

void cgrpyyset_debug (int debug_flag  );

YY_EXTRA_TYPE cgrpyyget_extra (void );

void cgrpyyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *cgrpyyget_in (void );

void cgrpyyset_in  (FILE * in_str  );

FILE *cgrpyyget_out (void );

void cgrpyyset_out  (FILE * out_str  );

int cgrpyyget_leng (void );

char *cgrpyyget_text (void );

int cgrpyyget_lineno (void );

void cgrpyyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int cgrpyywrap (void );
#else
extern int cgrpyywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( cgrpyytext, cgrpyyleng, 1, cgrpyyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( cgrpyyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( cgrpyyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, cgrpyyin))==0 && ferror(cgrpyyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(cgrpyyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int cgrpyylex (void);

#define YY_DECL int cgrpyylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after cgrpyytext and cgrpyyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( cgrpyyleng > 0 ) \
		YY_CURRENT_BUFFER_LVALUE->yy_at_bol = \
				(cgrpyytext[cgrpyyleng - 1] == '\n'); \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 744 "cgrp-lexer.l"




    /*
     * Notes:
     *   To avoid having to separate parsers, we need two entry points to
     *   the parser. The first one is for parsing a full configuration file
     *   including global options, partitions, groups, and rules. The second
     *   is for parsing an additional set of add-on classification rules.
     *
     *   To accomplish this while still being able to share the productions of
     *   the two parsers we
     *     1) fork the parser at the top level production
     *     2) have the parser control which parser is to be used (lexer_type)
     *     3) have the lexer emit type-specific start-symbols to activate the
     *        correct parser
     */
    
    if (lexer_start_token != 0) {
        int start_token;

        start_token       = lexer_start_token;
        lexer_start_token = 0;

        return start_token;
    }



#line 1669 "lex.cgrpyy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! cgrpyyin )
			cgrpyyin = stdin;

		if ( ! cgrpyyout )
			cgrpyyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			cgrpyyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				cgrpyy_create_buffer(cgrpyyin,YY_BUF_SIZE );
		}

		cgrpyy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of cgrpyytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 407 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 777 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
*yy_cp = (yy_hold_char); /* undo effects of setting up cgrpyytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up cgrpyytext again */
YY_RULE_SETUP
#line 774 "cgrp-lexer.l"
{ char path[PATH_MAX], *beg, *end;
                              int len;

			      if (lexer_noinclude)
			          return 1;                              
                              beg = strchr(cgrpyytext, '\''); beg++;
                              end = strchr(beg,    '\''); end--;
                              len = end - beg + 1;
                              if (len >= PATH_MAX)
                                  OHM_ERROR("cgrp: too long path '%s'", beg-1);
                              else {
                                  strncpy(path, beg, len);
                                  path[len] = '\0';
                                  lexer_push_input(path);
                              }
                            }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 793 "cgrp-lexer.l"
{ IGNORE(WHITESPACE);              }
	YY_BREAK
case 3:
*yy_cp = (yy_hold_char); /* undo effects of setting up cgrpyytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up cgrpyytext again */
YY_RULE_SETUP
#line 794 "cgrp-lexer.l"
{ IGNORE(COMMENT_FULL);
                              PUSH_BACK_EOL();                 }
	YY_BREAK
case 4:
*yy_cp = (yy_hold_char); /* undo effects of setting up cgrpyytext */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up cgrpyytext again */
YY_RULE_SETUP
#line 796 "cgrp-lexer.l"
{ IGNORE(COMMENT_TRAIL);
                              PUSH_BACK_EOL();                 }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 798 "cgrp-lexer.l"
{ IGNORE(CR);                      }
	YY_BREAK
case 6:
/* rule 6 can match eol */
YY_RULE_SETUP
#line 799 "cgrp-lexer.l"
{ PROCESS_EOL();                   }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 801 "cgrp-lexer.l"
{ PASS_KEYWORD(GLOBAL);            }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 802 "cgrp-lexer.l"
{ PASS_KEYWORD(PARTITION);         }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 803 "cgrp-lexer.l"
{ PASS_KEYWORD(DESCRIPTION);       }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 804 "cgrp-lexer.l"
{ PASS_KEYWORD(CPU_SHARES);        }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 805 "cgrp-lexer.l"
{ PASS_KEYWORD(MEM_LIMIT);         }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 806 "cgrp-lexer.l"
{ PASS_KEYWORD(REALTIME_LIMIT);    }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 807 "cgrp-lexer.l"
{ PASS_KEYWORD(PATH);              }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 808 "cgrp-lexer.l"
{ PASS_KEYWORD(RULE);              }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 809 "cgrp-lexer.l"
{ PASS_KEYWORD(GROUP);             }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 810 "cgrp-lexer.l"
{ PASS_KEYWORD(RENICE);            }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 811 "cgrp-lexer.l"
{ PASS_KEYWORD(SCHEDULE);          }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 812 "cgrp-lexer.l"
{ PASS_KEYWORD(USER);              }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 813 "cgrp-lexer.l"
{ PASS_KEYWORD(PARENT);            }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 814 "cgrp-lexer.l"
{ PASS_KEYWORD(BINARY);            }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 815 "cgrp-lexer.l"
{ PASS_KEYWORD(CMDLINE);           }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 816 "cgrp-lexer.l"
{ PASS_KEYWORD(NAME);              }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 817 "cgrp-lexer.l"
{ PASS_KEYWORD(TYPE);              }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 818 "cgrp-lexer.l"
{ PASS_KEYWORD(IGNORE);            }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 819 "cgrp-lexer.l"
{ PASS_KEYWORD(LEADS);             }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 820 "cgrp-lexer.l"
{ PASS_KEYWORD(RECLASS_AFTER);     }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 821 "cgrp-lexer.l"
{ PASS_KEYWORD(RECLASSIFY);        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 822 "cgrp-lexer.l"
{ PASS_KEYWORD(CLASSIFY);          }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 823 "cgrp-lexer.l"
{ PASS_KEYWORD(CLASSIFY_ARGVX);    }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 824 "cgrp-lexer.l"
{ PASS_KEYWORD(PRIORITY);          }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 825 "cgrp-lexer.l"
{ PASS_KEYWORD(OOM);               }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 826 "cgrp-lexer.l"
{ PASS_KEYWORD(RESPONSE_CURVE);    }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 827 "cgrp-lexer.l"
{ PASS_KEYWORD(NO_OP);             }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 828 "cgrp-lexer.l"
{ PASS_KEYWORD(EXPORT_GROUPS);     }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 829 "cgrp-lexer.l"
{ PASS_KEYWORD(EXPORT_PARTITIONS); }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 830 "cgrp-lexer.l"
{ PASS_KEYWORD(EXPORT_FACT);       }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 831 "cgrp-lexer.l"
{ PASS_KEYWORD(CGROUPFS_OPTIONS);  }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 832 "cgrp-lexer.l"
{ PASS_KEYWORD(CGROUP_CONTROL);    }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 833 "cgrp-lexer.l"
{ PASS_KEYWORD(IOWAIT_NOTIFY);     }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 834 "cgrp-lexer.l"
{ PASS_KEYWORD(IOQLEN_NOTIFY);     }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 835 "cgrp-lexer.l"
{ PASS_KEYWORD(SWAP_PRESSURE);     }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 836 "cgrp-lexer.l"
{ PASS_KEYWORD(ADDON_RULES);       }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 837 "cgrp-lexer.l"
{ PASS_KEYWORD(ALWAYS_FALLBACK);   }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 838 "cgrp-lexer.l"
{ PASS_KEYWORD(PRESERVE_PRIO);     }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 840 "cgrp-lexer.l"
{ PASS_TOKEN(HEADER_OPEN);         }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 841 "cgrp-lexer.l"
{ PASS_TOKEN(HEADER_CLOSE);        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 843 "cgrp-lexer.l"
{ PASS_NUMBER(ARG);                }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 844 "cgrp-lexer.l"
{ PASS_TOKEN(EQUAL);               }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 845 "cgrp-lexer.l"
{ PASS_TOKEN(NOTEQ);               }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 846 "cgrp-lexer.l"
{ PASS_TOKEN(LESS);                }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 847 "cgrp-lexer.l"
{ PASS_TOKEN(GREATER);             }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 848 "cgrp-lexer.l"
{ PASS_TOKEN(CURLY_OPEN);          }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 849 "cgrp-lexer.l"
{ PASS_TOKEN(CURLY_CLOSE);         }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 851 "cgrp-lexer.l"
{ PASS_TOKEN(AND);                 }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 852 "cgrp-lexer.l"
{ PASS_TOKEN(OR);                  }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 853 "cgrp-lexer.l"
{ PASS_TOKEN(NOT);                 }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 854 "cgrp-lexer.l"
{ PASS_TOKEN(IMPLIES);             }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 855 "cgrp-lexer.l"
{ PASS_TOKEN(SEMICOLON);           }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 856 "cgrp-lexer.l"
{ PASS_TOKEN(COMMA);               }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 857 "cgrp-lexer.l"
{ PASS_TOKEN(COLON);               }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 859 "cgrp-lexer.l"
{ PASS_TOKEN(ASTERISK);            }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 860 "cgrp-lexer.l"
{ PASS_STRING(IDENT);              }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 861 "cgrp-lexer.l"
{ PASS_STRING(PATH);               }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 862 "cgrp-lexer.l"
{ PASS_STRING(STRING);             }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 863 "cgrp-lexer.l"
{ PASS_NUMBER(DOUBLE);             }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 864 "cgrp-lexer.l"
{ PASS_NUMBER(UINT);               }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 865 "cgrp-lexer.l"
{ PASS_NUMBER(SINT);               }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 867 "cgrp-lexer.l"
{ int c;
			      if ((c = input()) != '\n')
			          unput(c);
			      else {
			          DEBUG("escaped \\n @ %s:%d",
				        lexer_file(), lexer_line());
			          lexer.input->line++;
			      }
			    }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 877 "cgrp-lexer.l"
{
                               if (!lexer.eof) {
                                   lexer.eof = TRUE;
                                   PROCESS_EOL();
                               }
                               else {
                                   lexer.eof = FALSE;
                                   if (!lexer_pop_input())
                                       yyterminate();
                               }
/* 
 * Local Variables:
 * c-basic-offset: 4
 * indent-tabs-mode: nil
 * End:
 * vim:set expandtab shiftwidth=4:
 */
                                                               }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 895 "cgrp-lexer.l"
ECHO;
	YY_BREAK
#line 2154 "lex.cgrpyy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed cgrpyyin at a new source and called
			 * cgrpyylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = cgrpyyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( cgrpyywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * cgrpyytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of cgrpyylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					cgrpyyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			cgrpyyrestart(cgrpyyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) cgrpyyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 407 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 407 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 406);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up cgrpyytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					cgrpyyrestart(cgrpyyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( cgrpyywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve cgrpyytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = (c == '\n');

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void cgrpyyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        cgrpyyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            cgrpyy_create_buffer(cgrpyyin,YY_BUF_SIZE );
	}

	cgrpyy_init_buffer(YY_CURRENT_BUFFER,input_file );
	cgrpyy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void cgrpyy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		cgrpyypop_buffer_state();
	 *		cgrpyypush_buffer_state(new_buffer);
     */
	cgrpyyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	cgrpyy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (cgrpyywrap()) processing, but the only time this flag
	 * is looked at is after cgrpyywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void cgrpyy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	cgrpyyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE cgrpyy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) cgrpyyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cgrpyy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) cgrpyyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in cgrpyy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	cgrpyy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with cgrpyy_create_buffer()
 * 
 */
    void cgrpyy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		cgrpyyfree((void *) b->yy_ch_buf  );

	cgrpyyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a cgrpyyrestart() or at EOF.
 */
    static void cgrpyy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	cgrpyy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then cgrpyy_init_buffer was _probably_
     * called from cgrpyyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void cgrpyy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		cgrpyy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void cgrpyypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	cgrpyyensure_buffer_stack();

	/* This block is copied from cgrpyy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from cgrpyy_switch_to_buffer. */
	cgrpyy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void cgrpyypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	cgrpyy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		cgrpyy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void cgrpyyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)cgrpyyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cgrpyyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)cgrpyyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in cgrpyyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE cgrpyy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) cgrpyyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in cgrpyy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	cgrpyy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to cgrpyylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       cgrpyy_scan_bytes() instead.
 */
YY_BUFFER_STATE cgrpyy_scan_string (yyconst char * yystr )
{
    
	return cgrpyy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to cgrpyylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE cgrpyy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) cgrpyyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in cgrpyy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = cgrpyy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in cgrpyy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up cgrpyytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		cgrpyytext[cgrpyyleng] = (yy_hold_char); \
		(yy_c_buf_p) = cgrpyytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		cgrpyyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int cgrpyyget_lineno  (void)
{
        
    return cgrpyylineno;
}

/** Get the input stream.
 * 
 */
FILE *cgrpyyget_in  (void)
{
        return cgrpyyin;
}

/** Get the output stream.
 * 
 */
FILE *cgrpyyget_out  (void)
{
        return cgrpyyout;
}

/** Get the length of the current token.
 * 
 */
int cgrpyyget_leng  (void)
{
        return cgrpyyleng;
}

/** Get the current token.
 * 
 */

char *cgrpyyget_text  (void)
{
        return cgrpyytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void cgrpyyset_lineno (int  line_number )
{
    
    cgrpyylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see cgrpyy_switch_to_buffer
 */
void cgrpyyset_in (FILE *  in_str )
{
        cgrpyyin = in_str ;
}

void cgrpyyset_out (FILE *  out_str )
{
        cgrpyyout = out_str ;
}

int cgrpyyget_debug  (void)
{
        return cgrpyy_flex_debug;
}

void cgrpyyset_debug (int  bdebug )
{
        cgrpyy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from cgrpyylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    cgrpyyin = stdin;
    cgrpyyout = stdout;
#else
    cgrpyyin = (FILE *) 0;
    cgrpyyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * cgrpyylex_init()
     */
    return 0;
}

/* cgrpyylex_destroy is for both reentrant and non-reentrant scanners. */
int cgrpyylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		cgrpyy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		cgrpyypop_buffer_state();
	}

	/* Destroy the stack itself. */
	cgrpyyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * cgrpyylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *cgrpyyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *cgrpyyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void cgrpyyfree (void * ptr )
{
	free( (char *) ptr );	/* see cgrpyyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 895 "cgrp-lexer.l"
