
#line 3 "lex.yy_videoep_.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define yy_create_buffer yy_videoep__create_buffer
#define yy_delete_buffer yy_videoep__delete_buffer
#define yy_flex_debug yy_videoep__flex_debug
#define yy_init_buffer yy_videoep__init_buffer
#define yy_flush_buffer yy_videoep__flush_buffer
#define yy_load_buffer_state yy_videoep__load_buffer_state
#define yy_switch_to_buffer yy_videoep__switch_to_buffer
#define yyin yy_videoep_in
#define yyleng yy_videoep_leng
#define yylex yy_videoep_lex
#define yylineno yy_videoep_lineno
#define yyout yy_videoep_out
#define yyrestart yy_videoep_restart
#define yytext yy_videoep_text
#define yywrap yy_videoep_wrap
#define yyalloc yy_videoep_alloc
#define yyrealloc yy_videoep_realloc
#define yyfree yy_videoep_free

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yy_videoep_restart(yy_videoep_in  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yy_videoep_leng;

extern FILE *yy_videoep_in, *yy_videoep_out;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yy_videoep_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yy_videoep_text again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yy_videoep_restart()), so that the user can continue scanning by
	 * just pointing yy_videoep_in at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yy_videoep_text is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yy_videoep_leng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yy_videoep_wrap()'s to do buffer switches
 * instead of setting up a fresh yy_videoep_in.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yy_videoep_restart (FILE *input_file  );
void yy_videoep__switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_videoep__create_buffer (FILE *file,int size  );
void yy_videoep__delete_buffer (YY_BUFFER_STATE b  );
void yy_videoep__flush_buffer (YY_BUFFER_STATE b  );
void yy_videoep_push_buffer_state (YY_BUFFER_STATE new_buffer  );
void yy_videoep_pop_buffer_state (void );

static void yy_videoep_ensure_buffer_stack (void );
static void yy_videoep__load_buffer_state (void );
static void yy_videoep__init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_videoep__flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_videoep__scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_videoep__scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_videoep__scan_bytes (yyconst char *bytes,int len  );

void *yy_videoep_alloc (yy_size_t  );
void *yy_videoep_realloc (void *,yy_size_t  );
void yy_videoep_free (void *  );

#define yy_new_buffer yy_videoep__create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yy_videoep_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_videoep__create_buffer(yy_videoep_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yy_videoep_ensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_videoep__create_buffer(yy_videoep_in,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yy_videoep_in = (FILE *) 0, *yy_videoep_out = (FILE *) 0;

typedef int yy_state_type;

extern int yy_videoep_lineno;

int yy_videoep_lineno = 1;

extern char *yy_videoep_text;
#define yytext_ptr yy_videoep_text

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yy_videoep_text.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yy_videoep_leng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 87
#define YY_END_OF_BUFFER 88
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[430] =
    {   0,
        0,    0,   88,   87,    2,    1,   87,   87,   86,   87,
       72,   73,   83,   81,   69,   82,   84,   63,   70,   76,
       68,   80,   66,   74,   87,   75,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   85,    2,    0,   67,    0,    4,
        0,   64,   65,   63,   77,   78,   71,   79,    0,   66,
        3,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   59,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   13,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,    0,   66,   66,   32,   66,   19,
       66,   66,   66,   66,   61,   66,   66,   66,   66,   66,
       66,   66,   39,    8,    0,   66,   66,   66,   66,   66,
       66,   66,   66,   10,   66,   66,   60,   17,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   49,   66,   66,
       66,   62,   66,   66,   66,   66,   36,   66,   66,   66,
       66,   66,   66,   66,   66,    0,   66,   66,    0,   66,

       66,   66,   66,   37,   66,   66,   66,   42,   66,   66,
        0,   14,   66,   66,    0,   66,    0,    0,   66,   66,
       66,   35,    0,   66,   66,   66,   66,   66,   18,   66,
       66,   56,   38,   66,   66,    0,   34,   66,   66,   66,
       66,   66,   66,    0,   66,   66,   66,   66,   66,   66,
       57,   66,   66,    0,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,    0,   66,   66,   55,
       66,   66,   41,   66,   66,   66,   66,    5,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   40,   33,    7,
       66,   66,    6,   66,   58,   31,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   47,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   30,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   23,   66,   66,   66,   66,
       66,   66,    9,   66,   66,   66,   66,   66,   66,   66,
       66,   48,   66,   66,   54,   66,   66,   66,   66,   66,
       66,   66,   20,   66,   66,   66,   29,    0,   66,   66,
       53,   66,   66,   66,   66,   66,   16,   66,   66,   66,
        0,   66,   66,   66,   66,   66,   66,   66,   12,   11,
       66,   66,   66,   15,   66,   22,   66,   66,   66,   66,

       66,   66,   51,   50,   44,   43,   66,   66,   21,   46,
       45,   66,   66,   66,   28,   52,   27,   66,   66,   66,
       66,   66,   24,   66,    0,   26,   66,   25,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    6,    7,    8,
        9,   10,   11,   12,   13,    1,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,    1,   17,
       18,   19,    1,    1,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       21,   22,   23,    1,   24,    1,   25,   26,   27,   28,

       29,   30,   31,   32,   33,   20,   34,   35,   36,   37,
       38,   39,   40,   41,   42,   43,   44,   45,   46,   47,
       48,   20,    1,   49,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[50] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    1,    3,    1,    1,    1,    1,    3,
        1,    1,    1,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    1
    } ;

static yyconst flex_int16_t yy_base[434] =
    {   0,
        0,    0,  172, 1364,  169, 1364,  163,  162, 1364,  155,
     1364, 1364, 1364,  144, 1364,  132, 1364,  130, 1364,  124,
       32,   99,   39, 1364,  101, 1364,   40,   43,   42,   41,
       48,   45,   64,   62,   78,   49,   82,   84,   85,   86,
       92,  106,  108,  111, 1364,   94,   86, 1364,   86, 1364,
       75,   59,   45,   44, 1364, 1364, 1364, 1364,  112,  113,
     1364,  114,  120,  127,  130,  133,  137,  139,  136,  142,
      151,  156,  161,  164,  166,  171,  173,  181,  174,  176,
      178,  191,  194,  198,  200,  203,  210,  213,  215,  217,
      223,  235,  239,  236,  242,  244,  245,  254,  248,  258,

      252,  261,  275,  278,  279,  280,  282,  283,  287,  288,
      300,  303,  305,  306,  307,  304,  319,  325,  326,  327,
      329,  328,  331,  332,  333,  349,  350,  351,  355,  356,
      370,  372,  373,  374,  380,  387,  382,  392,  394,  396,
      399,  401,  408,  409,  416,  417,  418,  421,  424,  425,
      426,  441,  433,  438,  442,  443,  446,  447,  450,  460,
      462,  465,  467,  479,  480,  484,  485,  486,  487,  499,
      492,  501,  502,  507,  508,  514,  509,  521,  526,  529,
      534,  536,  538,  543,  544,  546,  548,  551,  553,  558,
      560,  561,  565,  566,  568,  570,  573,  580,  582,  587,

      588,  595,  601,  609,  610,  611,  615,  616,  617,  623,
      625,  630,  631,  632,  637,  639,  646,  645,  647,  661,
      652,  667,  668,  670,  674,  677,  683,  686,  687,  689,
      690,  696,  699,  702,  705,  708,  709,  712,  715,  717,
      724,  722,  725,  737,  731,  744,  746,  749,  752,  753,
      750,  758,  762,  754,  756,  774,  779,  781,  786,  784,
      788,  789,  791,  794,  796,  813,  815,  816,  817,  818,
      822,  820,  823,  825,  839,  843,  844,  845,  846,  848,
      851,  861,  864,  865,  867,  870,  873,  874,  883,  886,
      887,  888,  891,  896,  900,  901,  904,  906,  908,  909,

      910,  914,  918,  931,  932,  933,  936,  941,  948,  949,
      953,  954,  956,  963,  966,  968,  969,  971,  970,  972,
      990,  992,  993,  997,  998, 1000, 1005, 1006, 1007, 1014,
     1015, 1023, 1019, 1020, 1032, 1033, 1037, 1041, 1042, 1045,
     1047, 1049, 1057, 1059, 1067, 1069, 1072, 1073, 1074, 1076,
     1077, 1079, 1081, 1091, 1093, 1099, 1101, 1100, 1103, 1106,
     1113, 1115, 1122, 1123, 1127, 1125, 1129, 1131, 1135, 1137,
     1144, 1149, 1150, 1151, 1152, 1159, 1166, 1171, 1174, 1175,
     1178, 1180, 1181, 1188, 1190, 1194, 1195, 1204, 1197, 1217,
     1219, 1221, 1222, 1223, 1225, 1227, 1229, 1231, 1239, 1243,

     1245, 1248, 1246, 1249, 1251, 1253, 1258, 1263, 1265, 1266,
     1267, 1268, 1275, 1280, 1271, 1281, 1283, 1288, 1285, 1287,
     1289, 1302, 1305, 1306, 1307, 1308, 1309, 1312, 1364, 1354,
     1357, 1360,   54
    } ;

static yyconst flex_int16_t yy_def[434] =
    {   0,
      429,    1,  429,  429,  429,  429,  430,  431,  429,  432,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  433,  429,  429,  429,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  429,  429,  430,  429,  431,  429,
      432,  429,  429,  429,  429,  429,  429,  429,  433,  433,
      429,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,

      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,

      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,

      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,

      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,    0,  429,
      429,  429,  429
    } ;

static yyconst flex_int16_t yy_nxt[1414] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   23,   27,   23,   28,   29,   30,   31,
       23,   32,   33,   23,   23,   34,   35,   36,   37,   23,
       38,   39,   40,   41,   42,   43,   44,   23,   45,   56,
       57,   59,   59,   59,   59,   59,   60,   59,   54,   53,
       59,   59,   59,   59,   59,   59,   59,   64,   59,   73,
       67,   59,   59,   52,   59,   69,   59,   70,   62,   68,
       71,   48,   63,   65,   66,   59,   74,   59,   50,   48,
       59,   72,   80,   75,   59,   46,   59,   59,   59,   77,

       76,   59,   78,   61,   59,   59,   79,   59,   59,   59,
       89,   86,   84,   87,   81,   59,   58,   90,   59,   82,
       59,   85,   83,   59,   59,   59,   59,   88,   92,   59,
       93,   59,   59,   91,   59,   59,   59,   59,   94,   59,
       96,   55,   59,   59,   54,   59,   53,   95,   59,   59,
       59,   59,   98,   59,   59,   97,   59,   99,   52,   59,
       59,   48,   59,   59,   50,   59,   48,  100,   59,  107,
       46,  429,  101,   59,   59,  104,   59,  106,   59,   59,
      102,  103,  105,   59,   59,   59,   59,   59,   59,   59,
       59,  108,  109,   59,   59,  110,   59,   59,  429,   59,

      114,   59,  429,   59,   59,  429,   59,  429,  429,  112,
       59,  111,   59,  113,   59,   59,  115,   59,  117,  116,
      429,   59,   59,   59,  118,   59,   59,   59,  429,   59,
      429,  120,  119,   59,  429,   59,   59,  122,   59,  121,
       59,  125,  429,  123,  429,  128,   59,   59,   59,  124,
      429,   59,  429,  126,   59,  127,   59,  135,   59,   59,
       59,  129,   59,  132,   59,   59,   59,   59,   59,  429,
       59,   59,  429,   59,  429,   59,  130,   59,  140,  131,
      134,   59,  136,  138,   59,  139,  429,   59,  137,  133,
       59,   59,   59,  429,   59,   59,  429,  141,   59,   59,

       59,   59,   59,   59,  144,   59,   59,  142,  145,  429,
       59,   59,   59,  148,  146,   59,  155,   59,   59,   59,
      143,  429,  429,   59,  147,  429,   59,   59,   59,   59,
       59,   59,  149,  152,  153,  154,  150,   59,   59,   59,
       59,   59,   59,   59,   59,   59,  151,  429,   59,   59,
       59,   59,   59,  157,   59,   59,   59,  156,  158,  162,
      429,   59,   59,   59,  429,  159,  160,   59,   59,  429,
      161,  164,   59,   59,   59,  163,  429,  429,   59,   59,
      166,  165,   59,  168,   59,   59,   59,  167,  169,  429,
      429,  429,   59,   59,   59,   59,   59,   59,  429,   59,

      171,  173,  170,   59,   59,   59,   59,  429,   59,  172,
       59,   59,  429,   59,  176,   59,  429,   59,  174,   59,
       59,   59,   59,  175,   59,  178,  177,  179,   59,   59,
       59,   59,   59,   59,  180,  429,   59,   59,   59,   59,
       59,   59,  429,  181,   59,   59,  182,   59,   59,   59,
       59,  186,  185,   59,   59,   59,   59,  429,   59,   59,
      183,   59,   59,  184,   59,   59,   59,  429,  187,   59,
       59,  188,   59,   59,  196,  429,  429,   59,  194,   59,
      192,  189,  429,   59,  429,   59,  191,  190,   59,  193,
       59,  199,   59,  197,  195,  198,   59,   59,   59,   59,

      429,  429,   59,   59,   59,  429,  429,   59,   59,   59,
       59,   59,  201,   59,   59,   59,  200,  202,  429,   59,
       59,   59,   59,  203,   59,   59,   59,  205,  429,  204,
       59,   59,   59,  211,  429,  208,  429,   59,   59,  206,
      209,   59,  429,  429,   59,  210,   59,  207,   59,   59,
      215,  429,   59,  213,  212,   59,  217,   59,  218,   59,
       59,   59,  214,   59,  429,   59,   59,   59,  429,   59,
       59,   59,   59,  223,   59,  216,   59,   59,   59,  219,
       59,   59,   59,   59,   59,   59,  429,  220,   59,   59,
      221,   59,   59,   59,   59,  429,   59,  224,  429,   59,

       59,  429,  222,   59,  429,   59,  225,   59,  227,  229,
       59,   59,  226,   59,  429,  228,  230,  232,   59,  429,
      429,   59,  236,   59,   59,  231,  235,   59,   59,   59,
      233,  234,   59,   59,   59,   59,  429,   59,   59,   59,
       59,  239,   59,   59,  244,  429,   59,  240,   59,   59,
      429,   59,  238,   59,   59,   59,  237,   59,   59,   59,
       59,  241,   59,  242,   59,  429,  245,  429,   59,   59,
       59,  243,  248,   59,  429,   59,  247,  429,  246,  254,
       59,  249,   59,  250,   59,  252,   59,  251,  253,   59,
       59,   59,  429,   59,  429,   59,  429,   59,   59,   59,

       59,   59,   59,  255,  429,  258,   59,  256,   59,   59,
       59,   59,   59,   59,   59,  261,  257,   59,  260,   59,
       59,  267,   59,  259,   59,   59,  262,   59,   59,   59,
      263,   59,   59,  429,   59,   59,   59,   59,   59,  264,
       59,  429,  429,   59,  265,   59,  266,   59,   59,   59,
      268,  270,  271,  273,   59,  276,   59,  269,   59,  272,
       59,   59,   59,  274,   59,   59,   59,   59,   59,   59,
       59,  429,   59,   59,   59,   59,   59,   59,  275,   59,
      280,   59,  278,  279,  282,   59,   59,  277,  429,  283,
      281,   59,  284,   59,  285,  286,   59,   59,   59,  287,

       59,   59,   59,   59,   59,  429,   59,   59,   59,   59,
      288,   59,   59,  429,   59,  429,  293,   59,  295,   59,
      292,  290,  296,  291,  297,   59,  289,   59,   59,   59,
       59,  294,   59,  429,   59,   59,   59,   59,   59,   59,
       59,   59,  429,   59,  301,   59,   59,  299,   59,  302,
      298,   59,  303,  300,  429,   59,   59,   59,   59,  305,
       59,  304,   59,   59,  429,  306,   59,   59,   59,   59,
      308,   59,  429,   59,   59,  307,   59,   59,  310,   59,
      429,  429,   59,  309,   59,   59,   59,   59,   59,  312,
       59,  315,  311,   59,  429,   59,   59,   59,   59,   59,

       59,  313,  316,   59,  429,  314,   59,  317,   59,   59,
       59,   59,   59,   59,   59,  319,   59,  429,   59,   59,
       59,   59,   59,   59,   59,  318,   59,   59,  320,   59,
       59,   59,   59,   59,  321,  323,  429,   59,  429,  429,
      429,   59,  327,   59,   59,   59,  429,  322,   59,  324,
      325,  326,  429,   59,   59,   59,   59,  330,  429,   59,
       59,   59,  429,  328,   59,   59,   59,  332,   59,  329,
      331,   59,   59,  334,  333,   59,   59,   59,   59,   59,
       59,   59,   59,   59,   59,  335,   59,  429,  429,   59,
      429,   59,   59,   59,   59,   59,  429,  429,  339,  341,

      337,  336,   59,  429,   59,   59,  343,  342,  338,   59,
       59,  340,   59,   59,  344,   59,   59,   59,   59,   59,
       59,   59,  429,   59,  345,  429,   59,   59,   59,   59,
       59,   59,   59,  351,  346,   59,  348,   59,   59,  429,
      347,  429,   59,   59,   59,   59,   59,  349,  350,   59,
      352,  354,  355,   59,   59,   59,   59,   59,  353,   59,
       59,   59,  356,  429,   59,   59,  429,  429,   59,   59,
       59,   59,   59,  359,  357,  358,  429,  361,  360,   59,
       59,   59,   59,  429,   59,  368,   59,  362,   59,   59,
       59,   59,   59,   59,  363,   59,   59,   59,  429,   59,

       59,  364,   59,   59,   59,   59,  369,  366,  370,  365,
      371,   59,   59,   59,   59,   59,   59,  429,   59,  367,
      429,  372,   59,   59,   59,   59,   59,   59,  376,   59,
      378,  374,  373,  375,  381,   59,   59,   59,   59,   59,
      377,   59,  429,   59,  429,   59,   59,   59,   59,   59,
       59,  379,   59,  384,   59,  382,   59,  380,   59,  383,
       59,   59,   59,   59,   59,  429,  429,   59,  429,  385,
      429,   59,   59,   59,   59,   59,  386,  389,   59,  387,
      429,  388,   59,   59,  429,  429,   59,   59,  429,   59,
       59,  390,   59,   59,   59,  391,  392,   59,   59,  393,

       59,   59,   59,   59,   59,  394,   59,   59,  395,   59,
      397,   59,  429,   59,  429,  429,   59,   59,   59,  429,
       59,  429,  396,  403,  398,  399,  402,   59,  400,   59,
      401,   59,  404,   59,   59,   59,  429,   59,  429,   59,
       59,   59,   59,   59,   59,   59,   59,  405,   59,  406,
       59,   59,   59,  408,   59,   59,  409,   59,   59,  410,
       59,   59,   59,   59,  407,   59,   59,  411,   59,   59,
       59,   59,   59,  429,   59,   59,   59,   59,   59,   59,
       59,   59,  413,   59,  414,  412,   59,   59,   59,   59,
       59,   59,   59,   59,   59,   59,  429,   59,   59,   59,

       59,   59,  429,   59,   59,  415,   59,  419,   59,  416,
       59,   59,   59,  418,   59,  417,  420,  425,   59,   59,
       59,   59,  421,  429,   59,   59,  429,  422,   59,   59,
       59,   59,   59,  429,  423,   59,  428,  429,  429,  427,
      429,  429,  429,  429,  424,  429,  429,  429,  429,  429,
      429,  429,  429,  426,   47,  429,   47,   49,   49,   49,
       51,  429,   51,    3,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429
    } ;

static yyconst flex_int16_t yy_chk[1414] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,   21,
       21,   23,   27,   30,   29,   28,  433,   32,   54,   53,
       31,   36,   23,   27,   30,   29,   28,   28,   32,   32,
       29,   31,   36,   52,   34,   30,   33,   30,   27,   29,
       31,   51,   27,   28,   28,   34,   32,   33,   49,   47,
       35,   31,   36,   33,   37,   46,   38,   39,   40,   34,

       33,   35,   35,   25,   41,   37,   35,   38,   39,   40,
       40,   39,   38,   39,   37,   41,   22,   40,   42,   37,
       43,   38,   37,   44,   59,   60,   62,   39,   41,   42,
       42,   43,   63,   40,   44,   59,   60,   62,   42,   64,
       43,   20,   65,   63,   18,   66,   16,   42,   69,   67,
       64,   68,   62,   65,   70,   44,   66,   63,   14,   69,
       67,   10,   68,   71,    8,   70,    7,   64,   72,   70,
        5,    3,   65,   73,   71,   68,   74,   69,   75,   72,
       66,   67,   68,   76,   73,   77,   79,   74,   80,   75,
       81,   71,   72,   78,   76,   73,   77,   79,    0,   80,

       77,   81,    0,   82,   78,    0,   83,    0,    0,   76,
       84,   74,   85,   76,   82,   86,   78,   83,   80,   79,
        0,   84,   87,   85,   81,   88,   86,   89,    0,   90,
        0,   83,   82,   87,    0,   91,   88,   85,   89,   84,
       90,   88,    0,   86,    0,   90,   91,   92,   94,   87,
        0,   93,    0,   88,   95,   89,   96,   97,   92,   94,
       99,   91,   93,   94,  101,   95,   98,   96,   97,    0,
      100,   99,    0,  102,    0,  101,   92,   98,  101,   93,
       96,  100,   98,   99,  102,  100,    0,  103,   98,   95,
      104,  105,  106,    0,  107,  108,    0,  102,  103,  109,

      110,  104,  105,  106,  105,  107,  108,  103,  106,    0,
      109,  110,  111,  109,  107,  112,  116,  113,  114,  115,
      104,    0,    0,  111,  108,    0,  112,  116,  113,  114,
      115,  117,  110,  113,  114,  115,  111,  118,  119,  120,
      122,  121,  117,  123,  124,  125,  112,    0,  118,  119,
      120,  122,  121,  118,  123,  124,  125,  117,  119,  123,
        0,  126,  127,  128,    0,  120,  121,  129,  130,    0,
      122,  125,  126,  127,  128,  124,    0,    0,  129,  130,
      127,  126,  131,  129,  132,  133,  134,  128,  130,    0,
        0,    0,  135,  131,  137,  132,  133,  134,    0,  136,

      132,  134,  131,  135,  138,  137,  139,    0,  140,  133,
      136,  141,    0,  142,  137,  138,    0,  139,  135,  140,
      143,  144,  141,  136,  142,  141,  139,  142,  145,  146,
      147,  143,  144,  148,  143,    0,  149,  150,  151,  145,
      146,  147,    0,  144,  148,  153,  146,  149,  150,  151,
      154,  150,  149,  152,  155,  156,  153,    0,  157,  158,
      147,  154,  159,  148,  152,  155,  156,    0,  151,  157,
      158,  152,  160,  159,  161,    0,    0,  162,  159,  163,
      157,  152,    0,  160,    0,  161,  156,  155,  162,  158,
      163,  164,  165,  162,  160,  163,  166,  167,  168,  169,

        0,    0,  164,  165,  171,    0,    0,  166,  167,  168,
      169,  170,  166,  172,  173,  171,  165,  169,    0,  174,
      175,  177,  170,  170,  172,  173,  176,  172,    0,  171,
      174,  175,  177,  178,    0,  175,    0,  176,  179,  173,
      176,  180,    0,    0,  178,  177,  181,  174,  182,  179,
      183,    0,  180,  180,  179,  184,  185,  181,  186,  182,
      187,  183,  181,  188,    0,  189,  184,  185,    0,  186,
      190,  187,  191,  192,  188,  184,  189,  193,  194,  188,
      195,  190,  196,  191,  192,  197,    0,  189,  193,  194,
      190,  195,  198,  196,  199,    0,  197,  193,    0,  200,

      201,    0,  191,  198,    0,  199,  194,  202,  196,  197,
      200,  201,  195,  203,    0,  196,  198,  200,  202,    0,
        0,  204,  205,  206,  203,  199,  203,  207,  208,  209,
      201,  202,  204,  205,  206,  210,    0,  211,  207,  208,
      209,  209,  212,  213,  214,    0,  210,  210,  211,  215,
        0,  216,  207,  212,  213,  214,  206,  218,  217,  219,
      215,  211,  216,  211,  221,    0,  215,    0,  218,  217,
      219,  213,  217,  220,    0,  221,  216,    0,  215,  222,
      223,  218,  224,  218,  220,  220,  225,  219,  221,  226,
      222,  223,    0,  224,    0,  227,    0,  225,  228,  229,

      226,  230,  231,  223,    0,  226,  227,  224,  232,  228,
      229,  233,  230,  231,  234,  230,  225,  235,  228,  232,
      236,  237,  233,  227,  238,  234,  231,  239,  235,  240,
      234,  236,  237,    0,  242,  238,  241,  243,  239,  235,
      240,    0,    0,  245,  236,  242,  236,  241,  243,  244,
      238,  240,  241,  243,  245,  245,  246,  239,  247,  242,
      244,  248,  251,  244,  249,  250,  254,  246,  255,  247,
      252,    0,  248,  251,  253,  249,  250,  254,  244,  255,
      249,  252,  247,  248,  252,  253,  256,  246,    0,  253,
      250,  257,  254,  258,  254,  254,  260,  256,  259,  255,

      261,  262,  257,  263,  258,    0,  264,  260,  265,  259,
      256,  261,  262,    0,  263,    0,  261,  264,  263,  265,
      260,  258,  264,  259,  265,  266,  257,  267,  268,  269,
      270,  262,  272,    0,  271,  273,  266,  274,  267,  268,
      269,  270,    0,  272,  268,  271,  273,  267,  274,  269,
      266,  275,  271,  267,    0,  276,  277,  278,  279,  274,
      280,  272,  275,  281,    0,  275,  276,  277,  278,  279,
      277,  280,    0,  282,  281,  276,  283,  284,  280,  285,
        0,    0,  286,  279,  282,  287,  288,  283,  284,  282,
      285,  285,  281,  286,    0,  289,  287,  288,  290,  291,

      292,  283,  286,  293,    0,  284,  289,  287,  294,  290,
      291,  292,  295,  296,  293,  292,  297,    0,  298,  294,
      299,  300,  301,  295,  296,  291,  302,  297,  294,  298,
      303,  299,  300,  301,  297,  299,    0,  302,    0,    0,
        0,  303,  303,  304,  305,  306,    0,  298,  307,  300,
      301,  302,    0,  308,  304,  305,  306,  306,    0,  307,
      309,  310,    0,  304,  308,  311,  312,  308,  313,  305,
      307,  309,  310,  310,  309,  314,  311,  312,  315,  313,
      316,  317,  319,  318,  320,  311,  314,    0,    0,  315,
        0,  316,  317,  319,  318,  320,    0,    0,  316,  318,

      314,  313,  321,    0,  322,  323,  320,  319,  315,  324,
      325,  317,  326,  321,  321,  322,  323,  327,  328,  329,
      324,  325,    0,  326,  322,    0,  330,  331,  327,  328,
      329,  333,  334,  329,  324,  332,  326,  330,  331,    0,
      325,    0,  333,  334,  335,  336,  332,  327,  328,  337,
      330,  332,  333,  338,  339,  335,  336,  340,  331,  341,
      337,  342,  334,    0,  338,  339,    0,    0,  340,  343,
      341,  344,  342,  338,  335,  337,    0,  340,  339,  345,
      343,  346,  344,    0,  347,  348,  349,  341,  350,  351,
      345,  352,  346,  353,  342,  347,  348,  349,    0,  350,

      351,  344,  352,  354,  353,  355,  349,  346,  350,  345,
      351,  356,  358,  357,  354,  359,  355,    0,  360,  347,
        0,  353,  356,  358,  357,  361,  359,  362,  358,  360,
      360,  356,  354,  357,  363,  364,  361,  366,  362,  365,
      359,  367,    0,  368,    0,  363,  364,  369,  366,  370,
      365,  361,  367,  366,  368,  364,  371,  362,  369,  365,
      370,  372,  373,  374,  375,    0,    0,  371,    0,  368,
        0,  376,  372,  373,  374,  375,  368,  372,  377,  369,
        0,  370,  376,  378,    0,    0,  379,  380,    0,  377,
      381,  373,  382,  383,  378,  374,  375,  379,  380,  376,

      384,  381,  385,  382,  383,  378,  386,  387,  379,  389,
      381,  384,    0,  385,    0,    0,  388,  386,  387,    0,
      389,    0,  380,  387,  382,  383,  386,  388,  384,  390,
      385,  391,  388,  392,  393,  394,    0,  395,    0,  396,
      390,  397,  391,  398,  392,  393,  394,  391,  395,  392,
      396,  399,  397,  395,  398,  400,  397,  401,  403,  398,
      402,  404,  399,  405,  393,  406,  400,  399,  401,  403,
      407,  402,  404,    0,  405,  408,  406,  409,  410,  411,
      412,  407,  401,  415,  402,  400,  408,  413,  409,  410,
      411,  412,  414,  416,  415,  417,    0,  419,  413,  420,

      418,  421,    0,  414,  416,  407,  417,  414,  419,  408,
      420,  418,  421,  413,  422,  412,  418,  423,  424,  425,
      426,  427,  419,    0,  428,  422,    0,  420,  423,  424,
      425,  426,  427,    0,  421,  428,  427,    0,    0,  425,
        0,    0,    0,    0,  422,    0,    0,    0,    0,    0,
        0,    0,    0,  424,  430,    0,  430,  431,  431,  431,
      432,    0,  432,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,

      429,  429,  429,  429,  429,  429,  429,  429,  429,  429,
      429,  429,  429
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_videoep__flex_debug;
int yy_videoep__flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yy_videoep_text;
#line 1 "config-scanner.l"
/*****************************************************************************/
/*  Copyright (C) 2010 Nokia Corporation.                                    */
/*                                                                           */
/*  These OHM Modules are free software; you can redistribute                */
/*  it and/or modify it under the terms of the GNU Lesser General Public     */
/*  License as published by the Free Software Foundation                     */
/*  version 2.1 of the License.                                              */
/*                                                                           */
/*  This library is distributed in the hope that it will be useful,          */
/*  but WITHOUT ANY WARRANTY; without even the implied warranty of           */
/*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU         */
/*  Lesser General Public License for more details.                          */
/*                                                                           */
/*  You should have received a copy of the GNU Lesser General Public         */
/*  License along with this library; if not, write to the Free Software      */
/*  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 */
/*  USA.                                                                     */
/*****************************************************************************/
#line 21 "config-scanner.l"
#include <stdlib.h>
#include <stdio.h>
/* #include <string.h> */

#include "plugin.h"
#include "config-private.h"
#include "config-parser.h"

#define EOL_TOKEN                                          \
    do {                                                   \
        debug_append("EOL", NULL);                         \
        debug_flush();                                     \
        yy_videoep_lineno++;                               \
        yy_videoep_column.first = 0;                       \
        yy_videoep_column.last  = 0;                       \
        yy_videoep_lval.string = "<eol>";                  \
        return TKN_EOL;                                    \
    } while(0)


#define EOF_TOKEN                                          \
    do {                                                   \
        debug_append("EOF", NULL);                         \
        debug_flush();                                     \
        yy_videoep_lineno++;                               \
        yy_videoep_column.first = 0;                       \
        yy_videoep_column.last  = 0;                       \
        yy_videoep_lval.string = "<eof>";                  \
        yyterminate();                                     \
    } while(0)


#define CONTINUATION_TOKEN                                 \
    do {                                                   \
        yy_videoep_lineno++;                               \
        yy_videoep_column.first = 0;                       \
        yy_videoep_column.last  = 0;                       \
    } while(0)


#define VALUELESS_TOKEN(t)                                 \
    do {                                                   \
        debug_append(#t, NULL);                            \
        token_to_string(TKN_##t);                          \
        return TKN_##t;                                    \
    } while(0)

#define STRING_TOKEN(t)                                    \
    do {                                                   \
        debug_append(#t, yy_videoep_text);                          \
        save_string(yy_videoep_text);                               \
        return TKN_##t;                                    \
    } while(0)


#define YY_USER_ACTION                                     \
    {                                                      \
        yy_videoep_column.first = yy_videoep_column.last;  \
        yy_videoep_column.last += yy_videoep_leng;         \
    }

static inline int yy_videoep_wrap(void)
{
    return 1;
}


YYSTYPE   yy_videoep_lval;
yy_column yy_videoep_column;

static char  dbgbuf[4096];
static char *dbgend = dbgbuf + sizeof(dbgbuf);
static char *dbgptr = dbgbuf;

static void  token_to_string(int);
static void  save_string(const char *);
static void  debug_append(const char *, const char *);
static void  debug_flush(void);

#line 1021 "lex.yy_videoep_.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yy_videoep_lex_destroy (void );

int yy_videoep_get_debug (void );

void yy_videoep_set_debug (int debug_flag  );

YY_EXTRA_TYPE yy_videoep_get_extra (void );

void yy_videoep_set_extra (YY_EXTRA_TYPE user_defined  );

FILE *yy_videoep_get_in (void );

void yy_videoep_set_in  (FILE * in_str  );

FILE *yy_videoep_get_out (void );

void yy_videoep_set_out  (FILE * out_str  );

int yy_videoep_get_leng (void );

char *yy_videoep_get_text (void );

int yy_videoep_get_lineno (void );

void yy_videoep_set_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yy_videoep_wrap (void );
#else
extern int yy_videoep_wrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yy_videoep_text, yy_videoep_leng, 1, yy_videoep_out )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yy_videoep_in )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yy_videoep_in ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yy_videoep_in))==0 && ferror(yy_videoep_in)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yy_videoep_in); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yy_videoep_lex (void);

#define YY_DECL int yy_videoep_lex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yy_videoep_text and yy_videoep_leng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 199 "config-scanner.l"


#line 1206 "lex.yy_videoep_.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yy_videoep_in )
			yy_videoep_in = stdin;

		if ( ! yy_videoep_out )
			yy_videoep_out = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yy_videoep_ensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_videoep__create_buffer(yy_videoep_in,YY_BUF_SIZE );
		}

		yy_videoep__load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yy_videoep_text. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 430 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1364 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 201 "config-scanner.l"
{ EOL_TOKEN;          }
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 202 "config-scanner.l"
{ EOF_TOKEN;          }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 203 "config-scanner.l"
{ /* ignore */        }
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 204 "config-scanner.l"
{ CONTINUATION_TOKEN; }
	YY_BREAK
case 4:
*yy_cp = (yy_hold_char); /* undo effects of setting up yy_videoep_text */
(yy_c_buf_p) = yy_cp -= 1;
YY_DO_BEFORE_ACTION; /* set up yy_videoep_text again */
YY_RULE_SETUP
#line 205 "config-scanner.l"
{ /* ignore */        }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 207 "config-scanner.l"
{ VALUELESS_TOKEN (FUNCTION);          }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 208 "config-scanner.l"
{ VALUELESS_TOKEN (SEQUENCE);          }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 209 "config-scanner.l"
{ VALUELESS_TOKEN (RESOLVER);          }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 211 "config-scanner.l"
{ VALUELESS_TOKEN (NAME);              }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 212 "config-scanner.l"
{ VALUELESS_TOKEN (STEP_UNTIL);        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 213 "config-scanner.l"
{ VALUELESS_TOKEN (STEP);              }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 214 "config-scanner.l"
{ VALUELESS_TOKEN (FIRST_SUCCESS);     }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 215 "config-scanner.l"
{ VALUELESS_TOKEN (FIRST_FAILURE);     }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 216 "config-scanner.l"
{ VALUELESS_TOKEN (END);               }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 218 "config-scanner.l"
{ VALUELESS_TOKEN (DEVICE);            }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 219 "config-scanner.l"
{ VALUELESS_TOKEN (OUT_SIGNAL);        }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 220 "config-scanner.l"
{ VALUELESS_TOKEN (OUT_RATIO);         }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 221 "config-scanner.l"
{ VALUELESS_TOKEN (TYPE);              }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 222 "config-scanner.l"
{ VALUELESS_TOKEN (SCREEN);            }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 223 "config-scanner.l"
{ VALUELESS_TOKEN (CRTC);              }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 224 "config-scanner.l"
{ VALUELESS_TOKEN (ROOT_WINDOW);       }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 225 "config-scanner.l"
{ VALUELESS_TOKEN (ROOT_WINDOW_ID);    }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 226 "config-scanner.l"
{ VALUELESS_TOKEN (ROOT_PROPERTY);     }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 227 "config-scanner.l"
{ VALUELESS_TOKEN (NEW_WINDOW);        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 228 "config-scanner.l"
{ VALUELESS_TOKEN (APP_WINDOW);        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 229 "config-scanner.l"
{ VALUELESS_TOKEN (APP_WINDOW_ID);     }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 230 "config-scanner.l"
{ VALUELESS_TOKEN (APP_PROPERTY);      }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 231 "config-scanner.l"
{ VALUELESS_TOKEN (WIN_PROPERTY);      }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 232 "config-scanner.l"
{ VALUELESS_TOKEN (OUT_PROPERTY);      }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 233 "config-scanner.l"
{ VALUELESS_TOKEN (XV_PROPERTY);       }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 234 "config-scanner.l"
{ VALUELESS_TOKEN (WIN_ID);            }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 235 "config-scanner.l"
{ VALUELESS_TOKEN (VARIABLE);          }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 236 "config-scanner.l"
{ VALUELESS_TOKEN (ATOM);              }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 237 "config-scanner.l"
{ VALUELESS_TOKEN (PROPERTY);          }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 238 "config-scanner.l"
{ VALUELESS_TOKEN (WINDOW);            }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 239 "config-scanner.l"
{ VALUELESS_TOKEN (OUTPUT);            }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 240 "config-scanner.l"
{ VALUELESS_TOKEN (INPUT);             }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 241 "config-scanner.l"
{ VALUELESS_TOKEN (VIDEO);             }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 242 "config-scanner.l"
{ VALUELESS_TOKEN (TARGET);            }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 243 "config-scanner.l"
{ VALUELESS_TOKEN (MODE);              }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 244 "config-scanner.l"
{ VALUELESS_TOKEN (POSITION);          }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 245 "config-scanner.l"
{ VALUELESS_TOKEN (DONTCARE);          }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 246 "config-scanner.l"
{ VALUELESS_TOKEN (APPEND);            }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 248 "config-scanner.l"
{ VALUELESS_TOKEN (HSYNC_POSITIVE);    }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 249 "config-scanner.l"
{ VALUELESS_TOKEN (HSYNC_NEGATIVE);    }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 250 "config-scanner.l"
{ VALUELESS_TOKEN (VSYNC_POSITIVE);    }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 251 "config-scanner.l"
{ VALUELESS_TOKEN (VSYNC_NEGATIVE);    }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 252 "config-scanner.l"
{ VALUELESS_TOKEN (INTERLACE);         }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 253 "config-scanner.l"
{ VALUELESS_TOKEN (DOUBLE_SCAN);       }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 254 "config-scanner.l"
{ VALUELESS_TOKEN (CSYNC);             }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 255 "config-scanner.l"
{ VALUELESS_TOKEN (CSYNC_POSITIVE);    }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 256 "config-scanner.l"
{ VALUELESS_TOKEN (CSYNC_NEGATIVE);    }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 257 "config-scanner.l"
{ VALUELESS_TOKEN (PIXEL_MULTIPLEX);   }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 258 "config-scanner.l"
{ VALUELESS_TOKEN (DOUBLE_CLOCK);      }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 259 "config-scanner.l"
{ VALUELESS_TOKEN (HALVE_CLOCK);       }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 261 "config-scanner.l"
{ VALUELESS_TOKEN (CARDINAL);          }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 262 "config-scanner.l"
{ VALUELESS_TOKEN (STRING);            }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 263 "config-scanner.l"
{ VALUELESS_TOKEN (INTEGER);           }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 264 "config-scanner.l"
{ VALUELESS_TOKEN (UNSIGNED);          }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 265 "config-scanner.l"
{ VALUELESS_TOKEN (IF);                }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 266 "config-scanner.l"
{ VALUELESS_TOKEN (THEN);              }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 267 "config-scanner.l"
{ VALUELESS_TOKEN (ELSE);              }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 268 "config-scanner.l"
{ VALUELESS_TOKEN (ENDIF);             }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 270 "config-scanner.l"
{ STRING_TOKEN    (UNSIGNED_NUMBER);   }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 271 "config-scanner.l"
{ STRING_TOKEN    (POSITIVE_NUMBER);   }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 272 "config-scanner.l"
{ STRING_TOKEN    (NEGATIVE_NUMBER);   }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 273 "config-scanner.l"
{ STRING_TOKEN    (IDENTIFIER);        }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 274 "config-scanner.l"
{ STRING_TOKEN    (TEXT);              }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 276 "config-scanner.l"
{ VALUELESS_TOKEN (ASSIGN);            }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 277 "config-scanner.l"
{ VALUELESS_TOKEN (COMMA);             }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 278 "config-scanner.l"
{ VALUELESS_TOKEN (COLON);             }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 279 "config-scanner.l"
{ VALUELESS_TOKEN (IMPLICATION);       }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 280 "config-scanner.l"
{ VALUELESS_TOKEN (OPEN_PARENTHESIS);  }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 281 "config-scanner.l"
{ VALUELESS_TOKEN (CLOSE_PARENTHESIS); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 282 "config-scanner.l"
{ VALUELESS_TOKEN (OPEN_BRACKET);      }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 283 "config-scanner.l"
{ VALUELESS_TOKEN (CLOSE_BRACKET);     }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 284 "config-scanner.l"
{ VALUELESS_TOKEN (LESS);              }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 285 "config-scanner.l"
{ VALUELESS_TOKEN (LESS_OR_EQUAL);     }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 286 "config-scanner.l"
{ VALUELESS_TOKEN (EQUAL);             }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 287 "config-scanner.l"
{ VALUELESS_TOKEN (GREATER_OR_EQUAL);  }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 288 "config-scanner.l"
{ VALUELESS_TOKEN (GREATER);           }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 289 "config-scanner.l"
{ VALUELESS_TOKEN (PLUS);              }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 290 "config-scanner.l"
{ VALUELESS_TOKEN (MINUS);             }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 291 "config-scanner.l"
{ VALUELESS_TOKEN (ASTERISK);          }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 292 "config-scanner.l"
{ VALUELESS_TOKEN (SLASH);             }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 293 "config-scanner.l"
{ VALUELESS_TOKEN (LOGICAL_OR);        }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 294 "config-scanner.l"
{ VALUELESS_TOKEN (LOGICAL_AND);       }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 298 "config-scanner.l"
ECHO;
	YY_BREAK
#line 1733 "lex.yy_videoep_.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yy_videoep_in at a new source and called
			 * yy_videoep_lex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yy_videoep_in;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yy_videoep_wrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yy_videoep_text, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yy_videoep_lex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_videoep_realloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yy_videoep_restart(yy_videoep_in  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yy_videoep_realloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 430 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 430 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 429);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yy_videoep_text */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yy_videoep_restart(yy_videoep_in );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yy_videoep_wrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yy_videoep_text */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yy_videoep_restart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yy_videoep_ensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_videoep__create_buffer(yy_videoep_in,YY_BUF_SIZE );
	}

	yy_videoep__init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_videoep__load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_videoep__switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yy_videoep_pop_buffer_state();
	 *		yy_videoep_push_buffer_state(new_buffer);
     */
	yy_videoep_ensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_videoep__load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yy_videoep_wrap()) processing, but the only time this flag
	 * is looked at is after yy_videoep_wrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_videoep__load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yy_videoep_in = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_videoep__create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yy_videoep_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_videoep__create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_videoep_alloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_videoep__create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_videoep__init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_videoep__create_buffer()
 * 
 */
    void yy_videoep__delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_videoep_free((void *) b->yy_ch_buf  );

	yy_videoep_free((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yy_videoep_restart() or at EOF.
 */
    static void yy_videoep__init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_videoep__flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_videoep__init_buffer was _probably_
     * called from yy_videoep_restart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_videoep__flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_videoep__load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yy_videoep_push_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yy_videoep_ensure_buffer_stack();

	/* This block is copied from yy_videoep__switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_videoep__switch_to_buffer. */
	yy_videoep__load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yy_videoep_pop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_videoep__delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_videoep__load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yy_videoep_ensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yy_videoep_alloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yy_videoep_ensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yy_videoep_realloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yy_videoep_ensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_videoep__scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_videoep_alloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_videoep__scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_videoep__switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yy_videoep_lex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_videoep__scan_bytes() instead.
 */
YY_BUFFER_STATE yy_videoep__scan_string (yyconst char * yystr )
{
    
	return yy_videoep__scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yy_videoep_lex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_videoep__scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yy_videoep_alloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_videoep__scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_videoep__scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_videoep__scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yy_videoep_text. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yy_videoep_text[yy_videoep_leng] = (yy_hold_char); \
		(yy_c_buf_p) = yy_videoep_text + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yy_videoep_leng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yy_videoep_get_lineno  (void)
{
        
    return yy_videoep_lineno;
}

/** Get the input stream.
 * 
 */
FILE *yy_videoep_get_in  (void)
{
        return yy_videoep_in;
}

/** Get the output stream.
 * 
 */
FILE *yy_videoep_get_out  (void)
{
        return yy_videoep_out;
}

/** Get the length of the current token.
 * 
 */
int yy_videoep_get_leng  (void)
{
        return yy_videoep_leng;
}

/** Get the current token.
 * 
 */

char *yy_videoep_get_text  (void)
{
        return yy_videoep_text;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yy_videoep_set_lineno (int  line_number )
{
    
    yy_videoep_lineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_videoep__switch_to_buffer
 */
void yy_videoep_set_in (FILE *  in_str )
{
        yy_videoep_in = in_str ;
}

void yy_videoep_set_out (FILE *  out_str )
{
        yy_videoep_out = out_str ;
}

int yy_videoep_get_debug  (void)
{
        return yy_videoep__flex_debug;
}

void yy_videoep_set_debug (int  bdebug )
{
        yy_videoep__flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yy_videoep_lex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yy_videoep_in = stdin;
    yy_videoep_out = stdout;
#else
    yy_videoep_in = (FILE *) 0;
    yy_videoep_out = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yy_videoep_lex_init()
     */
    return 0;
}

/* yy_videoep_lex_destroy is for both reentrant and non-reentrant scanners. */
int yy_videoep_lex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_videoep__delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yy_videoep_pop_buffer_state();
	}

	/* Destroy the stack itself. */
	yy_videoep_free((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yy_videoep_lex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yy_videoep_alloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yy_videoep_realloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yy_videoep_free (void * ptr )
{
	free( (char *) ptr );	/* see yy_videoep_realloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 298 "config-scanner.l"



/*****************************************************
 *
 *  scanner code
 *
 *****************************************************/

static void token_to_string(int token)
{
    static char *string;

    switch (token) {
    case TKN_EOL:                 string = "<eol>";                     break;
    case TKN_FUNCTION:            string = "function";                  break;
    case TKN_SEQUENCE:            string = "sequence";                  break;
    case TKN_RESOLVER:            string = "resolver";                  break;
    case TKN_NAME:                string = "name";                      break;
    case TKN_STEP_UNTIL:          string = "step-until";                break;
    case TKN_STEP:                string = "step";                      break;
    case TKN_FIRST_SUCCESS:       string = "first-success";             break;
    case TKN_FIRST_FAILURE:       string = "first-failure";             break;
    case TKN_END:                 string = "end";                       break;
    case TKN_ROOT_WINDOW:         string = "root-window";               break;
    case TKN_ROOT_WINDOW_ID:      string = "root-window-id";            break;
    case TKN_ROOT_PROPERTY:       string = "root-property";             break;
    case TKN_NEW_WINDOW:          string = "new-window";                break;
    case TKN_APP_WINDOW:          string = "application-window";        break;
    case TKN_APP_WINDOW_ID:       string = "application-window-id";     break;
    case TKN_APP_PROPERTY:        string = "application-property";      break;
    case TKN_WIN_PROPERTY:        string = "window-property";           break;
    case TKN_WIN_ID:              string = "window-id";                 break;
    case TKN_VARIABLE:            string = "variable";                  break;
    case TKN_ATOM:                string = "atom";                      break;
    case TKN_PROPERTY:            string = "property";                  break;
    case TKN_WINDOW:              string = "window";                    break;
    case TKN_CARDINAL:            string = "cardinal";                  break;
    case TKN_STRING:              string = "string";                    break;
    case TKN_INTEGER:             string = "integer";                   break;
    case TKN_UNSIGNED:            string = "unsigned";                  break;
    case TKN_IF:                  string = "if";                        break;
    case TKN_THEN:                string = "then";                      break;
    case TKN_ELSE:                string = "else";                      break;
    case TKN_ENDIF:               string = "endif";                     break;
    case TKN_ASSIGN:              string = "=";                         break;
    case TKN_COMMA:               string = ",";                         break;
    case TKN_COLON:               string = ":";                         break;
    case TKN_IMPLICATION:         string = "=>";                        break;
    case TKN_OPEN_PARENTHESIS:    string = "(";                         break;
    case TKN_CLOSE_PARENTHESIS:   string = ")";                         break;
    case TKN_OPEN_BRACKET:        string = "[";                         break;
    case TKN_CLOSE_BRACKET:       string = "]";                         break;
    case TKN_LESS:                string = "<";                         break;
    case TKN_LESS_OR_EQUAL:       string = "<=";                        break;
    case TKN_EQUAL:               string = "==";                        break;
    case TKN_GREATER_OR_EQUAL:    string = ">=";                        break;
    case TKN_GREATER:             string = ">";                         break;
    case TKN_PLUS:                string = "+";                         break;
    case TKN_MINUS:               string = "-";                         break;
    case TKN_ASTERISK:            string = "*";                         break;
    case TKN_SLASH:               string = "/";                         break;
    default:                      string = "";                          break;
    }

    yy_videoep_lval.string = string;
}

static void save_string(const char *string)
{
    static char  ringbuf[256];
    static char *bufptr;

    const char  *src;
    char         quoted;

    for (;;) {
        if (bufptr < ringbuf || bufptr >= ringbuf + sizeof(ringbuf))
            bufptr = ringbuf;

        yy_videoep_lval.string = bufptr;
        src = string;

        switch (src[0]) {
        case '\'':   quoted = '\'';   src++;  break;
        case '\"':   quoted = '\"';   src++;  break;
        default:     quoted = 0xff;           break;
        }

        while (bufptr < ringbuf + sizeof(ringbuf)) {
            if ((*bufptr++ = *src++) == '\0') {
                if (bufptr[-2] == quoted)
                    bufptr[-2] = '\0';
                return;
            }
        }
    }
}

static void debug_append(const char *token, const char *value)
{
    if (!DBG_SCAN)
        return;

    if (dbgptr < dbgend) {
        if (value == NULL)
            dbgptr += snprintf(dbgptr, dbgend-dbgptr, ":%s", token); 
        else
            dbgptr += snprintf(dbgptr, dbgend-dbgptr, ":%s[%s]", token, value);
    }
}

static void debug_flush(void)
{
    if (dbgptr > dbgbuf) {
        OHM_DEBUG(DBG_SCAN, "line %d: %s\n", yy_videoep_lineno,
                  dbgbuf + ((dbgbuf[0] == ':') ? 1:0));
        dbgptr = dbgbuf;
        dbgptr[0] = '\0';
    }
}

int scanner_open_file(const char *path)
{
    if (!path || !(yy_videoep_in = fopen(path, "r")))
        return -1;

    return 0;
}





/*
 * Local Variables:
 * c-basic-offset: 4
 * indent-tabs-mode: nil
 * End:
 * vim:set expandtab shiftwidth=4:
 */

